### ISSUE TITLE
Failed to load Core on Windows

### ISSUE THREAD

**Issue by Zewwy** [libretro/ludo#125]
When I try to load a game in Ludo, it asks me to load a core first,

this kind of sucks compared to the logic of Lakka, which asks to pick from a list of cores after selecting a game to load.

So ok, go to cores, pick any core from the list, and you'll simply be greeted with failed to load core.

**Comment by RobLoach** [comment]
Posted my logs of this happening on Windows over at: https://github.com/libretro/ludo/issues/89#issuecomment-456521619

```
ludo -L "C:\Users\rob_l\Desktop\Ludo\cores\nestopia_libretro.dll" "10-Yard Fight (Japan).zip"
panic: Failed to load C:\Users\rob_l\Desktop\Ludo\cores\nestopia_libretro.dll: The specified module could not be found.        
goroutine 1 [running, locked to thread]:
main.main() 

C:/Users/travis/gopath/src/github.com/libretro/ludo/main.go:101 +0x604                
```                                                                                                                                                  

This affects Windows, but not Linux.

**Comment by Zewwy** [comment]
correct, all verisons of Windows.

**Comment by kivutar** [comment]
I've tested the latest release, and can't reproduce this bug. I'm on Windows 10 64bit.
I was able to launch Super Bomberman 5 on snes9x.

**Comment by Zewwy** [comment]
Not sure what details you want, regardless if I try ludo on Windows 7 or Windows 10. It simply fails to load the cores. Let me get you some snippets.... 

https://i.imgur.com/sthxW5r.png

**Comment by Zewwy** [comment]
It maybe a dependency thing, can you enlighten me on how to get this GLFW dependency?

all your instruction state is

"On Windows
Setup openal headers and dll in mingw-w64 include and lib folders."

I've been a windows admin for a long time and these instructions mean literally nothing to me. I managed to get the compiled Windows x64 binaries, but they are simply dll's and do not have a installation package. So I have no idea where I should put these?

**Comment by kivutar** [comment]
> It maybe a dependency thing, can you enlighten me on how to get this GLFW dependency?

No, the loading of a DLL has nothing to do with GLFW which is a graphic library.

And GLFW doesn't need installation for Ludo, as it is statically linked in it.

It must be something else, something trickier. See https://blog.pcrisk.com/windows/12626-how-to-fix-qthe-specified-module-could-not-be-foundq-error

> "Setup openal headers and dll in mingw-w64 include and lib folders"
> I've been a windows admin for a long time and these instructions mean literally nothing to me.

Let me give you more detailed instructions: https://github.com/libretro/ludo/blob/master/.travis.yml#L72-L79

Can you tell me the versions of Ludo and Windows you're using? Including processor architecture (32bit or 64bit), please.

**Comment by Zewwy** [comment]
Those details are in both images I shared above :D

AFAIK it can't run on 32bit, so both are 64 bit. Running only the latest build of Ludo 0.2.7.

Checking your references now. Thanks for the help.

**Comment by Zewwy** [comment]
Just for quick sakes test on My Windows 10 1709 x64 workstation at work, since I'm literally running out of windows machines to try and guess what...

Same error

**Comment by kivutar** [comment]
OK thanks for this precious informations. I'll make this a top priority issue, as I want to support Windows.
But I need to find a way to reproduce this bug on my machine.

**Comment by kivutar** [comment]
I've created a branch with an automated test for core launching.

The test is passing on my local windows, invoked from Bash and from Cmd:

![capture](https://user-images.githubusercontent.com/442722/51783378-31aab880-216b-11e9-9e75-cd576c22f11c.PNG)

We'll see if I can make it pass on Travis.

**Comment by kivutar** [comment]
OK I'm now able to reproduce on Travis.

This `exit status 3221225781` that we see during `go test` is related to a DLL issue, according to https://github.com/hybridgroup/gocv/issues/38

The solution will certainly be related to the CGO flags.

**Comment by Zewwy** [comment]
Thanks for all your hard work on this!

**Comment by kivutar** [comment]
No problem. I'm a little bit stuck on this one however, can somebody try to setup the official OpenAL and OpenAL SDK from https://www.openal.org/ and see if it fixes it with either the Ludo release or a freshly compiled Ludo?

**Comment by kivutar** [comment]
OK thanks for the test. You did what I meant.

**Comment by Zewwy** [comment]
Oh that Win---Dohs!!!

**Comment by kivutar** [comment]
I've tested one thing: removing OpenAL from the branch. And the issue is still there. Which means that the problem happens when loading the libretro core DLL or OpenGL. Not OpenAL.

**Comment by Zewwy** [comment]
mhm strange... what could be special about your windows to make the loading work... But fail on all my Windows machines and Robs...

**Comment by kivutar** [comment]
I honestly don't know.

If it was OpenAL, I could think that it was due to the fact that I have a few SDK installed on my windows.

But currently I don't know which DLL fails to load. We need to find a way to know that.

**Comment by kivutar** [comment]
See also https://github.com/golang-ui/nuklear/issues/12

**Comment by Zewwy** [comment]
well I'm not sure what any of that means, but I did what I could to help,

So I ran proc mon, Here's running Ludo after clearing out all the "noise"

![](https://i.imgur.com/aghdfzs.png)

 to see what was happening when I attempted to load a core...

![](https://i.imgur.com/TJj0Qq5.png)

**Comment by Zewwy** [comment]
Best I could find about this dll is its linked to minGW64? [Source](https://stackoverflow.com/questions/28907304/cc1-exe-system-error-libwinpthread-1-dll-missing-but-it-isnt)

Also maybe this thread is of help?

https://github.com/HaxeFoundation/hxcpp/issues/339

**Comment by kivutar** [comment]
I've published a new release that includes this DLL. Can you try again with this please?
I was able to run it and load a core using `wine`.
It's still failing in Travis however. So I'm not sure if the fix is enough.

**Comment by Zewwy** [comment]
I'll grab the latest build and run another test. Thanks again. :)

**Comment by kivutar** [comment]
OK it's cool that this bug is finally fixed.
We can discuss your 4 points on Discord, as this thread is only about the DLL issue.
And the issue tracker is not the right place to have conversations and brainstorms.
