### ISSUE TITLE
Switch to a better playlist format

### ISSUE THREAD

**Issue by kivutar** [libretro/ludo#134]
We're currently using the old playlist format from RetroArch.
RetroArch now supports a new extensible JSON format.

Switching to the new JSON format has been considered, but would be painful because of the closing `]` at the end of the file, preventing us to append easily. We would have to keep all of the playlists into memory, which may be a lot of memory.

Something like CSV would be a good compromise.

**Comment by kivutar** [comment]
It's not a bit more processing, it's a lot more processing!

**Comment by RobLoach** [comment]
:+1:

**Comment by Zewwy** [comment]
I second CSV, simple and effective.
