### ISSUE TITLE
Mac OS X issues

### ISSUE THREAD

**Issue by Fatty69420** [libretro/ludo#151]
Doesn’t work on Mac OS X Mojave,
Failed to find suitable pixel format

**Comment by fmaida** [comment]
That's strange, I'm using Ludo 0.3.5 on a MacBook Air running Mojave and it's working.

**Comment by Fatty69420** [comment]
That’s strange, just opens and closes for me.
Even using it with wine just doesn’t work.

**Comment by Fatty69420** [comment]
But I’m using ludo 0.3.7 so :/

**Comment by Fatty69420** [comment]
Just tried 0.3.5 and it also doesn’t work

**Comment by kivutar** [comment]
Can you `/Applications/Ludo.app/Contents/MacOS` and `./ludo -v`
To have an error log?

**Comment by Fatty69420** [comment]
In the morning

**Comment by Fatty69420** [comment]
Sorry that I am responding so late, got home from class a while ago, let me run that.

**Comment by Fatty69420** [comment]
![Image](https://i.imgur.com/hySemGO.jpg)

**Comment by kivutar** [comment]
Ah that's something new...
What core were you launching? Or it was just the UI?

**Comment by kivutar** [comment]
Try things like:

```
./ludo -glver=4.5
```

```
./ludo -glver=4.1
```

```
./ludo -glver=3.2
```

```
./ludo -glver=3.0
```

```
./ludo -glver=2.1
```

Just to see if one of them works. Please.

**Comment by Fatty69420** [comment]
I will later today

**Comment by kivutar** [comment]
Apparently, many users are experiencing similar issues with GLFW based programs on OSX.

It would be good for us to know your hardware, especially the graphic card.

**Comment by Fatty69420** [comment]
Intel core i7
16GB ram
GTX 950
1Tb hard disk
Mac OS X Mojave

**Comment by kivutar** [comment]
OK, I'll try this https://stackoverflow.com/questions/27365099/nsgl-failed-to-create-opengl-pixel-format

**Comment by kivutar** [comment]
@Fatty69420 please try http://static.kivutar.me/Ludo-OSX-x86_64-stencil8bit.dmg

**Comment by Fatty69420** [comment]
I will when I get home

**Comment by Fatty69420** [comment]
im going to try it right now

**Comment by Fatty69420** [comment]
```
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: NSGL: Failed to find a suitable pixel format
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: NSGL: Failed to find a suitable pixel format

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.2/glfw.acceptError(0xc0000b7ce8, 0x2, 0x2, 0x0, 0x0)
	/Users/kivutar/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/error.go:177 +0x1ba
github.com/go-gl/glfw/v3.2/glfw.CreateWindow(0x3c0, 0x21c, 0x43ef113, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/kivutar/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/window.go:288 +0x17b
github.com/libretro/ludo/video.(*Video).Configure(0xc0004d4080, 0xc0004d4000)
	/Users/kivutar/ludo/video/video.go:145 +0x9a
github.com/libretro/ludo/video.Init(0xc000092800, 0xc000092670, 0x3, 0x0)
	/Users/kivutar/ludo/video/video.go:60 +0x63
main.main()
	/Users/kivutar/ludo/main.go:94 +0x3fc
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by kivutar** [comment]
OK, so it was not what I initially thought.

Though one. I'm going to have to borrow a few laptops from friends and family to test, because I feel like shooting in the dark..

**Comment by kivutar** [comment]
What was the result for `./ludo -glver=2.1` ?

**Comment by kivutar** [comment]
Closing this for now, as I can't reproduce and don't get replies after a month.
