### ISSUE TITLE
Use as a library 

### ISSUE THREAD

**Issue by blankenshipz** [libretro/ludo#153]
I'm new to libretro in general so this question might be misinformed or misplaced. It seems like a front-end is responsible for loading the core and interacting with the main program running within the core; with this in mind Is it possible to use `ludo` as an API to interact with a core programmatically? In the same way that [gym-retro](https://github.com/openai/retro#gym-retro) uses `libretro`

**Comment by RobLoach** [comment]
What are you trying to do? Trying to make a libretro core using Go? Trying to make a game using libretro and Go?

**Comment by blankenshipz** [comment]
@RobLoach I'd like to use the API to play games (cores?) with Machine Learning techniques.

**Comment by kivutar** [comment]
You can do this either using the low level https://github.com/libretro/ludo/tree/master/libretro package or using the higher level packages like `core` `input` and `video`.
I think you don't need menu, savestates, settings, options...

**Comment by blankenshipz** [comment]
@kivutar Are there some examples or tests that exist that might point me in the right direction on how to load a core and begin to interact with it?

**Comment by kivutar** [comment]
Yes, the integration tests core_test.go.

`core.Load` to load the libretro core.
`core.LoadGame` to load the game.
then `state.Global.Core.Run()`

See the runloop in main.go too.

A good exercice to understand a codebase is to remove some code. So try to clone Ludo and remove features you don't need.

**Comment by blankenshipz** [comment]
@kivutar Awesome! This should get me started; I'll open different issues if I have specific questions. 

Thanks again.
