### ISSUE TITLE
Xbox One gamepad not working on UI or gameplay.

### ISSUE THREAD

**Issue by VinnyFonseca** [libretro/ludo#171]
It recognises it being connected and disconnected, but not response from inputs.

![screenshot_00316](https://user-images.githubusercontent.com/1447185/53526740-ec1c3b00-3adc-11e9-9526-539bcd820688.png)

![screenshot_00317](https://user-images.githubusercontent.com/1447185/53526739-ec1c3b00-3adc-11e9-97a9-238af43d80cb.png)

**Comment by kivutar** [comment]
Are you on Windows, Linux or OSX?

**Comment by VinnyFonseca** [comment]
Ubuntu 18.10

**Comment by kivutar** [comment]
Does it work in utilities like `jstest`?
Can you run ludo with the -v flag and see what's the name of the joypad when you plug it?

**Comment by VinnyFonseca** [comment]
Yes, it works in jstest fine, I actually used it to set Steam compatibility and fix some conflicts.

This is what `-v` shows to me:

```
ludo -v
2019/03/02 19:07:58 [Video]: OpenGL version: 3.2.0 NVIDIA 415.27
2019/03/02 19:08:05 [Input]: Joystick #1 plugged: Microsoft X-Box One S pad.
```

**Comment by VinnyFonseca** [comment]
Well, and now it's working. I also had my G27 wheel connected and it was recognised as Joystick #0. I still think controller recognition should be better, or work with multiple input types, but the bug I raised is not valid as it is working with the controller, you just need to plug it first.

**Comment by kivutar** [comment]
OK thanks for reporting.
Any idea of why it wasn't working in the first place?

**Comment by VinnyFonseca** [comment]
Yes. Basically, if you have multiple connected controllers (Logitech G27, in my case) and they occupy Joy#0, then Joy#1 (Xbox One controller) does not work in UI or gameplay.

Steam also creates a phantom Xbox 360 controller, but that is always added after the original Xbox controller has been connected, so it always takes one position after.

From what I understand based on my usage, The order the controllers are connected dictate the order of players (P1, P2, etc). I had the wheel and the controller both connected at boot, wheel gets recognised first, becomes Joy#0, therefore P1, and P2 (Joy#1, Xbox One controller) cannot control the UI or play games that are single player.

Does it make sense?
