### ISSUE TITLE
Some systems are not being recognised.

### ISSUE THREAD

**Issue by VinnyFonseca** [libretro/ludo#172]
I scanned my entire rom folder which contains the following systems:

![screenshot_00319](https://user-images.githubusercontent.com/1447185/53527287-7618d380-3ade-11e9-8c06-d05a3e5bf1f6.png)

but all that was found were these systems:

![screenshot_00318](https://user-images.githubusercontent.com/1447185/53526865-40271f80-3add-11e9-9707-a5df9212039a.png)

The roms for SNES, N64 and Gamecube, for example, are recognised in retroarch.

**Comment by kivutar** [comment]
SNES scans well for me. Can you give details (checksums) of your SNES roms?

N64, Wii, GameCube, DS are not yet supported because Ludo doesn't have GL cores support yet.

**Comment by VinnyFonseca** [comment]
How do I get checksums? They all have a `.smc` extension, and there are 659 of them.

**Comment by VinnyFonseca** [comment]
Sorry, didn't mean to close it, slicked by mistake.

**Comment by RobLoach** [comment]
https://www.google.com/search?q=get+crc+value+from+file&oq=get+crc+value+from+file&aqs=chrome..69i57j33l3.5361j0j4&client=ms-android-google&sourceid=chrome-mobile&ie=UTF-8

**Comment by kivutar** [comment]
I think that no-intro SNES roms are all .sfc, not .smc

**Comment by RobLoach** [comment]
```
supported_extensions = "smc|sfc|swc|fig|bs"
```

**Comment by RobLoach** [comment]
This? https://github.com/libretro/ludo/pull/178 ... We could eventually have it parse the .info files of installed cores.

**Comment by kivutar** [comment]
Should be fixed in the latest release
