### ISSUE TITLE
Adding new filters/shaders

### ISSUE THREAD

**Issue by ghost** [libretro/ludo#187]
Awesome project! :+1: 
Wish from a humble user: please let us add more filters/shaders to Ludo.

https://github.com/libretro/common-shaders
https://www.retroarch.com/index.php?page=shaders
https://www.superrune.com/tools/supercrt.php

**Comment by RobLoach** [comment]
Ludo aims to be minimalist in its approach. If you have some favourites, they could be options, but we won't be adding all.

**Comment by kivutar** [comment]
I may add a few 1 pass shaders that are fast enough to work on even weak platforms. As we already have some code ready for that. But no multipass.

**Comment by kivutar** [comment]
I've added a CRT shader
