### ISSUE TITLE
Is Ludo replacing the retroarch scanner too?

### ISSUE THREAD

**Issue by i30817** [libretro/ludo#203]
If so i'm interested in proposing two 'extensions' to the scanner concept in retroarch that i find it unlikely xmb is going to support because they'd require complex dependencies i doubt will work on console ports and the first won't work on windows.

https://github.com/libretro/RetroArch/issues/8873 <-take advantage of extended attributes to get a 'stand in' for retrieving the crc32 instead of calculating it (like retroarch already does for zip files). As explained in the issue this also solves the case of softpatches crc not matching the final crc32 the core sees (if you use [my tool](https://github.com/i30817/rhdndat) to create the xattributes) and 'solve' the case the roms that the emulator writes to in normal operation and therefore change its checksum much later when you try to reconstruct the playlist (though i prefer to use system copy-on-write to keep the original rom, it's also helpful there, because you can still rescan the 'altered' copy on the copy on write). In fact extended attributes are great because they move with the file.

https://github.com/libretro/RetroArch/issues/8672 <- give the user complete control over the scanner behavior with files on the rom dirs filesystem. Helpful to pass launcher files to cores that need it, disassociate those launcher files from the roms that have the actual crc but still use it, being faster by whitelisting the types the scanner scans per directory subtree, allow to use multiple types of scan if you implement them, etc. 

It's a complex idea, so it needs to be read (both posts), but the tl;dr is : users that don't care can use the dumb scan and get false positives (because RA is scanning file cues when it should be track 1's because it needs cues to get a complete index file, or is using serials that misidentify hacks as the original game etc) or waste a lot of cpu power crc32'ing things they don't need. Users that care organize their games per console / required launcher file, and drop scanner control files into the file hierarchy.

**Comment by kivutar** [comment]
The scanner of Ludo is even more rudimentary than the one of RetroArch, as one of the design goal is to keep the codebase small.

Discussing these two proposals at the same time could become chaotic, so let's focus on the 1st one here, and we can then discuss the second proposal on a separate thread.

I have two questions about the extended attributes:
 - How does it work on Windows? I only want features that work on the 3 desktop OS
 - Does the user have to run a separate tool to populate the xattr? If so, I find it too unfriendly for Ludo's target audience

**Comment by i30817** [comment]
> How does it work on Windows? I only want features that work on the 3 desktop OS
there is a equivalent on NTFS but i don't know anything about it, since i haven't touched windows in 2 decades.

>    Does the user have to run a separate tool to populate the xattr? If so, I find it too unfriendly for Ludo's target audience

Not necessarily, i just find it attractive to *me* because it allow me to tie in the idea of attributes for checksums to softpatching (ie: in my tool, the 'user.rom.crc32' refers to the final patched file, even if it's a softpatch, which is something RA has problems with. You could easily tie in the scanner results to the files extended attributes for 'more of the same, but with a persistent cache now', it's just a wast imo.

**Comment by kivutar** [comment]
It's an interesting way of tackling the translation patch problem yes.

I had another plan for that: building and hosting a patch store. (I think it is legal to host patches)
With a web API to query them based on the checksum of the unpatched ROM.

However, Ludo doesn't even have the soft patching logic implemented. I've looked into it quickly, it's a medium amount of work. So the first step would be to support soft patching.

I wasn't aware of the problem of ROMs being modified by the emulator. In what cases does this happen?

**Comment by i30817** [comment]
All the computer cores, except sometimes they already adapted a adhoc 'copy on write' strategy to prevent this. Recently dosbox got a VFS of some kind because steam wants their game dirs to be read only now.

**Comment by i30817** [comment]
> It's an interesting way of tackling the translation patch problem yes.
> 
> I had another plan for that: building and hosting a patch store. (I think it is legal to host patches)
> With a web API to query them based on the checksum of the unpatched ROM.
> 

Another thing, this is ot always true (being 'legal' that is), and besides that hacks are getting larger and larger and sometimes more complex to apply. No emulation project - rightfully - wants to download 1 gb zips that when you open have 'first use $XCONSOLE_TOOL to sign the data with your private key'.

**Comment by i30817** [comment]
Uh sorry about the rants/derails when you said it would be too chaotic to discuss both ideas at the start. I can delete them if you want, the negativity isn't helping much there.

**Comment by kivutar** [comment]
No, keep them, it's valuable information for future developments

**Comment by kivutar** [comment]
I close this for now because it is too advanced for a frontend like Ludo
