### ISSUE TITLE
Clean up Variable API

### ISSUE THREAD

**Issue by RobLoach** [libretro/ludo#212]
When testing [Core Option Sublabels in a Core](https://github.com/libretro/RetroArch/pull/9092), I found when a core implementated core option sublabels, Ludo would crash:
https://github.com/libretro/RetroArch/pull/9092#issuecomment-510677368

```
➜  ludo git:(master) ./ludo -L ~/libretro-chailove/chailove_libretro.so ~/libretro-chailove/examples/bunnymark/main.chai
[ChaiLove] Initializing ChaiLove
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/libretro/ludo/libretro.(*Variable).Choices(0xc421abda48, 0xc4220ab540, 0x16, 0x1)
	/home/rob/.gocode/src/github.com/libretro/ludo/libretro/libretro.go:111 +0xc8
github.com/libretro/ludo/core.environmentGetVariable(0x7ffc419bfc50, 0x50)
	/home/rob/.gocode/src/github.com/libretro/ludo/core/environment.go:37 +0xe0
github.com/libretro/ludo/core.environment(0xc40000000f, 0x7ffc419bfc50, 0x7c7280)
	/home/rob/.gocode/src/github.com/libretro/ludo/core/environment.go:87 +0x12b
github.com/libretro/ludo/libretro.coreEnvironment(0xc40000000f, 0x7ffc419bfc50, 0x86e100)
	/home/rob/.gocode/src/github.com/libretro/ludo/libretro/libretro.go:483 +0x3f
github.com/libretro/ludo/libretro._cgoexpwrap_0624a055ae0e_coreEnvironment(0xffffffff0000000f, 0x7ffc419bfc50, 0xffffffffffffffff)
	_cgo_gotypes.go:668 +0x33
github.com/libretro/ludo/libretro._Cfunc_bridge_retro_load_game(0x7fce72ddad70, 0xc420127200, 0xc42009b200)
	_cgo_gotypes.go:416 +0x4a
github.com/libretro/ludo/libretro.(*Core).LoadGame.func1(0x7fce72ddad70, 0xc420127200, 0x92c7e30)
	/home/rob/.gocode/src/github.com/libretro/ludo/libretro/libretro.go:380 +0xd7
github.com/libretro/ludo/libretro.(*Core).LoadGame(0xc4247b2000, 0x7ffc419c0ff4, 0x42, 0xddc, 0x0, 0x0)
	/home/rob/.gocode/src/github.com/libretro/ludo/libretro/libretro.go:380 +0xa1
github.com/libretro/ludo/core.LoadGame(0x7ffc419c0ff4, 0x42, 0x0, 0x0)
	/home/rob/.gocode/src/github.com/libretro/ludo/core/core.go:143 +0x115
main.main()
	/home/rob/.gocode/src/github.com/libretro/ludo/main.go:115 +0x56c
```
@jdgleaver had some insight...

> Right, the crash is a result of Ludo playing fast and loose with the API..
> 
> Basically, it's just storing a pointer to the array of retro_variables passed to RETRO_ENVIRONMENT_SET_VARIABLES. This is not good. Nowhere in the spec does it say that anything passed to RETRO_ENVIRONMENT_SET_VARIABLES is persistent - the values should be parsed/cached by the frontend when the callback is called, not at some arbitrary point in the future.
> 
> The current libretro_core_options.h only creates a temporary retro_variable in the event that core options v1 is not supported - so of course, when Ludo tries to extract the variables long after the core has been loaded, there's nothing there.

Would be great to clean up the Ludo variable API usage to ensure cores that implement the new API don't crash Ludo.

**Comment by kivutar** [comment]
Thanks, looking into this...
