### ISSUE TITLE
Scrolling faster through library

### ISSUE THREAD

**Issue by vishesh** [libretro/ludo#216]
Currently, the only way to browse library is via `up` and `down` keys, which scroll one item at a time. This is not ideal for browsing through hundreds (or even < 100) games. I suggest using `left` and `right` arrows to scroll down/up by whole page.

I see in [menu/input.go:26](https://github.com/libretro/ludo/blob/master/menu/input.go#L26) that the scroll speed actually increases with long press, but it isn't fast enough. 

Ideally, it would be even better if we can filter, or "jump to letter" to directly jump to games starting with selected letter.

**Comment by kivutar** [comment]
I agree, we should implement jump to the next letter like in RetroArch, mapped to L and R

**Comment by RobLoach** [comment]
I like how Kodi manages its scrolling. Rather than L/R going letter by letter, it slowly increases the scroll speed.

**Comment by kivutar** [comment]
We also have this implemented, but it's not well tweaked.
