### ISSUE TITLE
 Audio bufsize to 1024 * 4 to will cause crash in some mednafen-psx rom 

### ISSUE THREAD

**Issue by giongto35** [libretro/ludo#219]
I run **Harvest Moon - Back to Nature (USA)** with mednafen-psx. The size of the audio buffer can go above 1024 * 4.
Why don't you just increase the bufSize because setting min here also doesn't produce correct sound.
https://github.com/libretro/ludo/blob/master/audio/audio.go#L89
I set bufSize to 1024 * 8 and it works nicely.

**Comment by kivutar** [comment]
It's something we have to test on every core, with many games. But why not.
