### ISSUE TITLE
BUG: Raspberry Pi 4 Cores Crashing

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#222]
I just installed ludo on my new raspberry pi 4 and noticed it crashing on core loads, navgating the menu seems fine. I have tried NES SNES and sega as well as gameboy. This doesn't appear to be affecting raspberry pi 3b+.

**Comment by kivutar** [comment]
To get logs, ssh in the machine (root:ludos) and `systemctl stop ludo` then start ludo manually with `ludo -v` and logs will be printed to stdout.

Thanks.

**Comment by johnnyq** [comment]
okay here is the logs for when I start dr Mario for gameboy. It loads I see the title screen and see press P to toggle menu on the top left but everything is frozen 

LudOS:~ # ludo -v
2019/08/29 14:52:51 [Video]: OpenGL version: 2.1 Mesa 19.1.2
2019/08/29 14:53:12 open /storage/.ludo/gambatte_libretro.json: no such file or directory
2019/08/29 14:53:12 [Core]: Name: Gambatte
2019/08/29 14:53:12 [Core]: Version: v0.5.0-netlink
2019/08/29 14:53:12 [Core]: Valid extensions: gb|gbc|dmg
2019/08/29 14:53:12 [Core]: Need fullpath: false
2019/08/29 14:53:12 [Core]: Block extract: false
2019/08/29 14:53:12 [Video]: Set Pixel Format: 2
Plain ROM loaded.
rambanks: 0
rombanks: 2
2019/08/29 14:53:12 [INFO]: [Gambatte]: Got internal game name: DR.MARIO.
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/pcm/pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
2019/08/29 14:53:12 al: cannot open the default audio device
2019/08/29 14:53:12 [OpenAL]: Using 4 buffers of 8192 bytes.
2019/08/29 14:53:12 [Core]: Game loaded: /storage/roms/Gameboy/Dr. Mario (World).zip

**Comment by johnnyq** [comment]
Here is a log when I launch Contra for NES I get a black screen with the Press P to toggle the menu

LudOS:~ # ludo -v
2019/08/29 14:57:46 [Video]: OpenGL version: 2.1 Mesa 19.1.2
2019/08/29 14:57:55 [Video]: Set Pixel Format: 2
2019/08/29 14:57:55 [INFO]: Frontend supports RGB565 - will use that instead of XRGB1555.
2019/08/29 14:57:55 [Core]: Name: FCEUmm
2019/08/29 14:57:55 [Core]: Version: (SVN) 81776d9
2019/08/29 14:57:55 [Core]: Valid extensions: fds|nes|unf|unif
2019/08/29 14:57:55 [Core]: Need fullpath: false
2019/08/29 14:57:55 [Core]: Block extract: false
2019/08/29 14:57:56 [INFO]: Loading /tmp/Contra (USA).nes...

2019/08/29 14:57:56 [INFO]:  ROM CRC32:  0xf6035030
2019/08/29 14:57:56 [INFO]:  ROM MD5:    0x5a5c2f4f1cafb1f55a8dc0d5ad4550e5
2019/08/29 14:57:56 [INFO]:  PRG ROM:    8 x 16KiB
2019/08/29 14:57:56 [INFO]:  CHR ROM:    0 x  8KiB
2019/08/29 14:57:56 [INFO]:  Mapper #:   2
2019/08/29 14:57:56 [INFO]:  Mapper name: UNROM
2019/08/29 14:57:56 [INFO]:  Mirroring: Vertical
2019/08/29 14:57:56 [INFO]:  Battery-backed: No
2019/08/29 14:57:56 [INFO]:  Trained: No
2019/08/29 14:57:56 [INFO]:  CHR-RAM:    8 KiB
2019/08/29 14:57:56 open /storage/.ludo/fceumm_libretro.json: no such file or directory
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib /home/kivutar/LudOS/build.LudOS-RPi4.arm/alsa-lib-1.1.9/src/pcm/pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
2019/08/29 14:57:56 al: cannot open the default audio device
2019/08/29 14:57:56 [OpenAL]: Using 4 buffers of 8192 bytes.
2019/08/29 14:57:56 [INFO]:  Player 1: Gamepad
2019/08/29 14:57:56 [INFO]:  Player 2: Gamepad
2019/08/29 14:57:56 [Core]: Game loaded: /storage/roms/Nintendo/Contra (USA).zip

**Comment by johnnyq** [comment]
and it appears to be the same for snes and sega just black frozen screens with Press P to toggle the menu. What I did notice though is gameboy is the only one that actually loads title screens then freezes while the other systems are just a black screen upon load

**Comment by johnnyq** [comment]
I just installed the v1.0-alpha19 ludos on my pi3b+ and now this is experiancing the same core crash issue as my raspberry pi 4. Is it just me or are guys experiancing the same. Im wondering if its how im restoring the image to the sd card. I use Gnome Disks to do so

**Comment by kivutar** [comment]
OK this is an issue related to alsa (audio).
Thanks for these useful logs.

**Comment by johnnyq** [comment]
From my Raspberry Pi 4 distroconfig.text does not contain dtparam=audio=on See Below

```
LudOS:/flash # cat distroconfig.txt 
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2019-present Team LibreELEC (https://libreelec.tv)

# WARNING: DO NOT EDIT THIS FILE - IT WILL BE OVERWRITTEN WHEN UPGRADING!
dtoverlay=vc4-fkms-v3d
disable_overscan=1
```

Here is my lsmod

```
Module                  Size  Used by
hci_uart               40960  1
serdev                 16384  1 hci_uart
btbcm                  16384  1 hci_uart
bluetooth             434176  21 hci_uart,btbcm
ecdh_generic           28672  2 bluetooth
8021q                  28672  0
brcmfmac              258048  0
brcmutil               16384  1 brcmfmac
bcm2835_codec          32768  0
videobuf2_dma_contig    20480  1 bcm2835_codec
snd_usb_audio         163840  0
bcm2835_mmal_vchiq     28672  1 bcm2835_codec
snd_hwdep              16384  1 snd_usb_audio
snd_usbmidi_lib        28672  1 snd_usb_audio
cfg80211              512000  1 brcmfmac
v4l2_mem2mem           20480  1 bcm2835_codec
videobuf2_memops       16384  1 videobuf2_dma_contig
videobuf2_v4l2         20480  2 bcm2835_codec,v4l2_mem2mem
videobuf2_common       36864  3 bcm2835_codec,v4l2_mem2mem,videobuf2_v4l2
rfkill                 24576  5 bluetooth,cfg80211
snd_rawmidi            28672  1 snd_usbmidi_lib
bcm2835_gpiomem        16384  0
videodev              143360  3 bcm2835_codec,v4l2_mem2mem,videobuf2_v4l2
rpivid_mem             16384  0
fixed                  16384  0



```

**Comment by johnnyq** [comment]
Alright!! everything worked when I added dtparam=audio=on to distroconfig.txt

**Comment by kivutar** [comment]
So now we need to understand why it wasn't there..

**Comment by johnnyq** [comment]
Hey @kivutar it looks like the issue has come back. I flashed the new 20 release using gnome disks and noticed that dtparam=audio=on was missing from distroconfig.txt

**Comment by kivutar** [comment]
Know this should be fixed.
