### ISSUE TITLE
Missing Close Content on menu toggle

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#224]
I noticed retroarch / lakka had a close content on their menu to exit the game that you are currently playing, but it is missing from Ludo. Maybe rename it to quit game for the awesome simplicity trend thats going on here with Ludo. Im really liking this setup

**Comment by kivutar** [comment]
I've removed it because I don't see the use of it. Loading another game automatically closes the previous running game. So in which case do you really need to close a game?

**Comment by bmertturk** [comment]
i am trying to use it on a windows tablet. without keyboard there is no exiting option if you dont't use it on the menu
