### ISSUE TITLE
Feature Request: Option to remove the flags next to the game

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#225]
This would be a fantastic feature to add to the settings menu, and maybe by default disable flags. I would rather just see the name of the game and nothing more to keep with the simplicity of the fantastic Ludo.

**Comment by kivutar** [comment]
Flags are in fact part of the name of the rom, displayed as icons to be shorter.
If we hide them, these is no way to differentiate between Crash Bandicoot (USA) and Crash Bandicoot (Japan) anymore.
So they need to stay.
