### ISSUE TITLE
Bug: Playstation Games not being added to the playlist

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#227]
I noticed the playstation games I have are not being added to the playlist when I scan. My files are in the the .bin .cue format. This did work in retroarch.

**Comment by kivutar** [comment]
RetroArch inspects the serial in the bin. Ludo is not that smart yet. It just looks for a cue to be exactly named like in the database.
You can browse the PSX database here https://db.libretro.com/Sony%20-%20PlayStation/index-0.html

It's very possible that the database itself contains wrong names and need fixes.

**Comment by johnnyq** [comment]
Perfect I I will try to match up the names

**Comment by kivutar** [comment]
We'll need to add Saga Frontier -> SaGa Frontier

**Comment by kivutar** [comment]
I close this, as this is more a bug of libretro-database
