### ISSUE TITLE
Feature Request: Friendly names for video filters

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#230]
To keep with the simplistic approach, maybe rename the video filters to more simple names like snes classic or nintendo classic. For example instead of zfast-crt just CRT Filter, Pixel Perfect, or Upscale etc.

**Comment by kivutar** [comment]
I was thinking about this too, but I don't know what friendly name could describe what `sharp-bilinear` really is.

**Comment by johnnyq** [comment]
Maybe just Sharp or Pixel Perfect

**Comment by kivutar** [comment]
OK why not. I'm waiting for more opinions on this. @RobLoach wdyt?

**Comment by RobLoach** [comment]
Think it's a great idea. The more user-friendly, the better. Good question around naming.... Hmmmm....

- Linear
- Sharp
- CRT
- Nearest

**Comment by kivutar** [comment]
What about:

 - Raw
 - Smooth
 - Sharp
 - CRT

(the default has been sharp-bilinear for a while)

**Comment by RobLoach** [comment]
Smooth and raw make sense 👍

**Comment by RobLoach** [comment]
I've seen "Pixel Perfect" used a lot too.

**Comment by johnnyq** [comment]
so CRT, Pixel Perfect, Original

**Comment by RobLoach** [comment]
Bilinear == "Blurry AF"
