### ISSUE TITLE
Bluetooth Controllers Not working

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#233]
I have a PS4 controller and have bluetooth on. When I plug it in, it works. I then unplug it and press the middle playstation button it blinks blue then solid blue and connects, ludo says wireless controller connected but the buttons do not work

**Comment by kivutar** [comment]
What procedure did you follow to pair the controller?

**Comment by johnnyq** [comment]
Here what I do

- Make sure bluetooth option is on in settings
- Turn off Pi4 and unplug PS4 controller
- Make sure PS4 controller blue light isnt on or flashing
- Turn on Pi4
- Plug PS4 controller in
The OSD says Jostick #0 plugged: Sony Interactive Entertainment Wireless Controller.
The PS4 controller lights up solid blue and it works
- Unplug the PS4 Controller
Joystick #0 unplugged 
Blue light is now out on the PS4 Controller
- Press Middle Playstation button
The Controller Blink blue for 2 secs then
Controller Turns solid blue
Then OSD says Joystick #0 plugged: Wireless Controller.

But the button do not work

**Comment by kivutar** [comment]
OK, you're trying a kind of auto pairing. There is no such feature in Ludo for now.

It's something that used to work on Lakka for the Dualshock 3.

On Ludo, I don't know yet if I should add auto pairing. Maybe a UI to pair any bluetooth device would fit better.

**Comment by johnnyq** [comment]
Okay that makes sense. I agree a UI would be awesome for pairing, maybe something in the settings menu. Also an option to auto reconnect to learned bluetooth controllers

**Comment by kivutar** [comment]
Auto reconnecting is already handled by bluez, so we don't have to implement it.

To implement an UI for pairing, we need to look into the dbus api of bluetoothctl or bluez.

**Comment by johnnyq** [comment]
I'm super excited for this feature thanks so much for your time

**Comment by johnnyq** [comment]
how do you currently pair a playstation 4 bluetooth controller in the meantime. I have bluetooth opion turned on in settings, but im not sure the best proper way to get it to work via command line.

**Comment by kivutar** [comment]
Just like in Lakka: https://www.lakka.tv/doc/wireless-dualshock/

**Comment by johnnyq** [comment]
I just got a Playstation 3 Controller for Christmas and I noticed something today when I unplugged the controller and pressed the Center home button it magically connected via Bluetooth. I don't know how but it did I wonder if we can get other bluetooth controllers to work the same way. plug them in then put in pair mode and they just connect

**Comment by kivutar** [comment]
You were on LudOS? Or just Ludo?

**Comment by johnnyq** [comment]
LudOS it was, if we can replicate this for other bluetooth controllers it would be fantastic!! I'm so happy with my PS3 controller.

**Comment by kivutar** [comment]
Maybe LibreELEC included the bluez patchset that allows DS3 auto pairing when plugged.

**Comment by kivutar** [comment]
Closing in favor of https://github.com/libretro/ludo/issues/339
