### ISSUE TITLE
Screen Tearing Occational frame skips in Emulators

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#237]
I noticed there has been some screen tearing mostly with SNES games especially contra 3 but I have noticed it in sega genesis and nintendo as well. I also noticed what appears to be the occational screen frame skipping. This was tested on the Raspberry Pi 4 i will test on the 3b+ to see if I get the same result

**Comment by kivutar** [comment]
I'm also experiencing this, but only on some TV.

**Comment by johnnyq** [comment]
Yeah same here, it doesn't affect me on my Sony TV but does happen on my Asus monitor

**Comment by kivutar** [comment]
Then it's going to be difficult to investigate. I have no idea how to debug this.
We can hope that a LibreELEC update or a GLFW update fixes it.

**Comment by kivutar** [comment]
It happens a lot with Genesis games.

**Comment by johnnyq** [comment]
This appears to be fixed on my end with the latest LudOS

**Comment by kivutar** [comment]
Even with Genesis games?

**Comment by johnnyq** [comment]
yes I started noticing this more im not sure what causes it

**Comment by kivutar** [comment]
Close as duplicate of https://github.com/libretro/ludo/issues/344
