### ISSUE TITLE
Can't open any MSX game

### ISSUE THREAD

**Issue by fmaida** [libretro/ludo#239]
Hello, I'm trying to load some MSX games from Ludo but I'm always getting an error.

I'm using macOS 10.14.6. I have successfully scanned some MSX roms, but when I try to launch one of them from Ludo I'm getting this error: "Failed to load the game".

I have taken a log file of the error and I'm attaching a copy of it to this ticket. On the log file I can see that Ludo tries to load a JSON file from my hard drive without success:

```
2019/09/09 12:03:16 open /Users/cesco/.ludo/bluemsx_libretro.json: no such file or directory

2019/09/09 12:03:16 [Core]: Name: blueMSX
2019/09/09 12:03:16 [Core]: Version: git ddd89ff
2019/09/09 12:03:16 [Core]: Valid extensions: rom|ri|mx1|mx2|dsk|col|sg|sc|cas|m3u
2019/09/09 12:03:16 [Core]: Need fullpath: true
2019/09/09 12:03:16 [Core]: Block extract: false
2019/09/09 12:03:16 [Video]: Set Pixel Format: 2
2019/09/09 12:03:16 [Menu]: failed to load the game
```

On my second attempt, I tried to load the bluemsx core to begin with, and then I tried to load a game, but I got the very same error:

```
2019/09/09 12:11:14 [Video]: OpenGL version: 4.1 INTEL-12.10.12
2019/09/09 12:11:19 open /Users/cesco/.ludo/bluemsx_libretro.json: no such file or directory
2019/09/09 12:11:19 [Core]: Name: blueMSX
2019/09/09 12:11:19 [Core]: Version: git ddd89ff
2019/09/09 12:11:19 [Core]: Valid extensions: rom|ri|mx1|mx2|dsk|col|sg|sc|cas|m3u
2019/09/09 12:11:19 [Core]: Need fullpath: true
2019/09/09 12:11:19 [Core]: Block extract: false
2019/09/09 12:11:19 [Core]: Core loaded: bluemsx_libretro.dylib
2019/09/09 12:11:31 [Video]: Set Pixel Format: 2
2019/09/09 12:11:31 [Core]: failed to load the game
```

On my third attempt, I have created an empty JSON file at ~/.ludo/bluemsx_libretro.json.
I saw on the log file that Ludo stopped complaining about the missing JSON file, but the game won't load anyway:

```
2019/09/09 12:15:00 [Video]: OpenGL version: 4.1 INTEL-12.10.12
2019/09/09 12:15:04 [Core]: Name: blueMSX
2019/09/09 12:15:04 [Core]: Version: git ddd89ff
2019/09/09 12:15:04 [Core]: Valid extensions: rom|ri|mx1|mx2|dsk|col|sg|sc|cas|m3u
2019/09/09 12:15:04 [Core]: Need fullpath: true
2019/09/09 12:15:04 [Core]: Block extract: false
2019/09/09 12:15:04 [Video]: Set Pixel Format: 2
2019/09/09 12:15:04 [Menu]: failed to load the game
```

I'm also attaching one of the MSX ROMs I can't load. It's a public domain game so I guess there shouldn't be any copyright problem.

I'm getting this error with every MSX rom I tried.

[test.log](https://github.com/libretro/ludo/files/3589898/test.log)

[Guru Logic (2003)(Karoshi)[RK701].zip](https://github.com/libretro/ludo/files/3589928/Guru.Logic.2003.Karoshi.RK701.zip)

**Comment by kivutar** [comment]
Weird, this rom is loading fine for me.

**Comment by fmaida** [comment]
Nope. My `~/.ludo/system/` folder is empty.

**Comment by kivutar** [comment]
OK I could reproduce with an empty `~/.ludo/system/` and I confirm that this is a bug.

I'll check if these files are supposed to be created automatically...

**Comment by kivutar** [comment]
Is it only macOS?

**Comment by fmaida** [comment]
I can also try this on a Raspberry Pi if it can help you.

**Comment by kivutar** [comment]
Try to copy the Machines folder like here https://docs.libretro.com/library/bluemsx/#bios

**Comment by flexiondotorg** [comment]
@kivutar I can confirm that copying the 'Databases' and 'Machines' Folders from [blueMSXv282full.zip](http://bluemsx.msxblue.com/rel_download/blueMSXv282full.zip) to the RetroArch System directory (as specified by `system_dir` in `ludo.toml`) makes all the MSX games playable.

**Comment by kivutar** [comment]
Thanks
