### ISSUE TITLE
new user. cant find keys

### ISSUE THREAD

**Issue by jjfmz42015** [libretro/ludo#241]
Im new to Ludo. I normally use standalone emus. 

Im liking Ludo.

Cant seem to find documentation on what Ludos hot keys are

I mean

F is enter exit fullscreen
P is pause which lets me get to Options for core.

WHat else exists? Is it documented somewhere for ppl new to the platform to see?

Thanks

**Comment by kivutar** [comment]
Hi, here are the hotkeys:

 - *F* fullscreen toggle
 - *ESC* quit
 - *P* menu toggle
 - *SPACE* fast forward toggle

I'll document them.

**Comment by jjfmz42015** [comment]
Thanks!!

**Comment by sangeet** [comment]
More detailed answer if someone is looking for it in the future: https://github.com/libretro/ludo/blob/master/input/binds_keyboard.go
