### ISSUE TITLE
bios aka firmware compatibility and locations please (as in where do I put them Win64)

### ISSUE THREAD

**Issue by jjfmz42015** [libretro/ludo#242]
bios aka firmware compatibility and locations please (as in where do I put them Win64)

**Comment by Lounes-Tb** [comment]
On RetroArch, you just put then in the \system folder (for mednafen_psx at least)
but in ludo, the folder just doesn't exist and creating it doesn't solve the problem either so it's a missing feature. And yes, I had the same problem.
Just use RetroArch for now, it doesn't have that problem

**Comment by Lounes-Tb** [comment]
I got a solution!
just change the location of the "System Directory" to wherever your bios files are
it was not a missing feature, it's a bug

**Comment by Lounes-Tb** [comment]
put them in C:\Users\(your user name)\.ludo\system
it confused me at first 'cause in retroarch, you can find \system in retroarch's folder
it was by coincidence that I found it
