### ISSUE TITLE
WIndows 64 bit fast forward broken

### ISSUE THREAD

**Issue by jjfmz42015** [libretro/ludo#243]
WIndows 64 bit build. 

Hit spacebar while in a game

fast forward message shows

game speed remains the same

**Comment by kivutar** [comment]
OK maybe vsync doesn't work the same on this driver

**Comment by jjfmz42015** [comment]
> OK maybe vsync doesn't work the same on this driver

was my fault. nvidia driver was set to force vsync always on. i set to application controled problem solved.

so not a bug sorry.

thank you.
