### ISSUE TITLE
GUI Fix: Press P to Toggle Menu

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#248]
When you start a game and a controller is plugged in, it says Press P to toggle menu instead it should show the controller hint to access menu.

**Comment by kivutar** [comment]
I agree with this. However the current notification system supports only text.
We would need to extend it to support icons too. And maybe icons in the middle of text.

**Comment by johnnyq** [comment]
you know I was thinking maybe we could just eliminate this notification and just show it as a hint at the bottom

**Comment by kivutar** [comment]
Yeah I was thinking about it too. It would be more consistent. If so, the hints need to be refactored to be drawable out of the menu. And also fade out.

**Comment by johnnyq** [comment]
Well I was thinking just to display it as a hint at the bottom with all the other hints, and to not show anything when you run a game.

**Comment by johnnyq** [comment]
I was rethinking this maybe we should just remove Press P to toggle menu

**Comment by kivutar** [comment]
Done
