### ISSUE TITLE
Feature Request: Video Filter Settings show example screenshot

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#249]
It would be awesome when you select between different video filters that it display a screenshot of what it may look like. Similar to NES Classic
![NESClassicDisplayOptions](https://user-images.githubusercontent.com/1812594/65713442-319ae980-e067-11e9-846e-dba8a42b6b67.jpg)

**Comment by kivutar** [comment]
It's hard to see the effect of a shader on a thumbnail. It's generally too small.

You can see the shader being updated live behind the scene. But it's currently a bit buggy, it will sometimes result in a black screen.

**Comment by johnnyq** [comment]
yeah I agree, but maybe not a screenshot but maybe a black and white image of a character or object. For CRT show the character or object with scan lines housed in an old TV just an idea. For another we could use a perfectly drawn character or object and another maybe a blocky character or object. These are just brain storming ideas ill look on the web for some more ideas

**Comment by kivutar** [comment]
Or we could have the dark background fade out, to see the game clearly, and being able to switch between shaders pressing left and right, with a visual hint.

Or we could present it in a separate menu like the current savestate menu.

In any case, a first step would be to fix this bug when we switch the shader.

**Comment by johnnyq** [comment]
I really Like this one 

"we could have the dark background fade out, to see the game clearly, and being able to switch between shaders pressing left and right, with a visual hint." 

Its Brilliant

Maybe even incorporate both.

**Comment by kivutar** [comment]
I think the live preview is enough, even if it's dark, we can still visualise the change
