### ISSUE TITLE
Feature Request: Option to Hide History

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#250]
Under settings give the option "Show History" On or Off button

**Comment by kivutar** [comment]
History is going to be move in another line above the hexagons on the main scene.

A bit like on the Switch.

The leftmost entry in the history will represent the currently running game and be linked to the quick menu.

I need to experiment a bit with this.

**Comment by johnnyq** [comment]
niceee sounds awesome!!

**Comment by kivutar** [comment]
So far my experiments are not very concluent. I was able to add this history line above the tabs and navigate them, but it doesn't look nice.

The fact that the games look differ so much from one console to another doesn't help to create unity between the entries.

I need the help of a pro UI designer there.
