### ISSUE TITLE
Feature Request: Automatic addition of games when put in the correct folder

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#253]
Rretropie does something of this sort, In the ROMs folder it lists all the game consoles and you just move the rom files into the corresponding game console folder. When you restart it should just automatically create the playlists based off what was added to the folder. This would eliminate adding games via Add Games and make it much easier for game management.

**Comment by kivutar** [comment]
We had this before in Lakka. It was before we had scanning in place.

The thing is that thumbnails are metadata are very linked to the scanning system.

Scanning can be slow on large collection of games. It's not like what RetroPie does, which is just listing files in directories.

So if we want to do things like RetroPie, we'd better move away from RetroArch scanning style. And this would mean redesigning how metadata and thumbnails work.

For example I doubt that RetroPie does the scrapping automatically on startup. Our current system achieves the same result as a scrapper, but eliminates the scrapping phase by relying on a local db.

So I'm not saying no, but if we go this way it's going to be a lot of redesign, and we need to think carefully and see if it's worth the effort.

**Comment by kivutar** [comment]
I close this for now, as the programs would hang up forever when we scan a very large filesystem.
It opens the door to too many nasty bugs.
