### ISSUE TITLE
Debugging a crash when I press a steam controller button

### ISSUE THREAD

**Issue by davidrenne** [libretro/ludo#256]
Are there some detailed logs that can tell me why the app crashes using this controller?  This is the only controller that navigates well for me and it crashes everytime I press the OK button.

I can single step the golang code too inside of GoLand from source if you can point me in the direction of where to set a debug break point I can press the button and see whats happening as to why it panics and exits for me.

**Comment by davidrenne** [comment]
Note this does the same thing on the compiled binary releases from the latest release yesterday and from source.  Maybe I should try an old version

**Comment by davidrenne** [comment]
Also note it only fails on pressing the B button.  Navigation works just fine and navigates the software.  I wish there were a button mapping setting somewhere.

**Comment by kivutar** [comment]
Do you have a PR with your configuration for this controller?

**Comment by davidrenne** [comment]
Can you explain how I can extract the name of the controller:

https://github.com/libretro/ludo/blob/master/input/binds_darwin.go#L6

And then know how to map each key like the xbox controller examples?  Does it merely match things by name and based on the hardware name?

I'd gladly test out and send a PR for my controller for each operating system and get it working if I knew a little more about how to match up my controller and map those values.  Steam controllers are pretty popular options and for some reason hooking up my xbox one controller via usb does not pick up and work.

When I plug it in, it doesnt popup with a controller name like other controllers do.

I confirmed that when I navigate into a menu using x and then press the B button on the steam controller, it does crash it.  So it's not like it's exiting due to being on the home screen and there being nowhere left to go.

Let me know a little more about how to match up my controller in binds files and ill try to get it working on a local build.

**Comment by davidrenne** [comment]
Gladly I got one of my controllers working.  PS3 is working fine now that I have read which controllers have mappings!  This is fun now that I have some controllers working, ludo is working nicely right out of the box.

**Comment by kivutar** [comment]
You can simply Println this variable: https://github.com/libretro/ludo/blob/master/input/input.go#L87

**Comment by kivutar** [comment]
OK I've plugged my Steam Controller on OSX and here is what happen:

The controller is recognized as a keyboard+mouse. The B key sends and ESC signal. So Ludo exists.

**Comment by kivutar** [comment]
To be able to use this controller, you would have to run Ludo through Steam, it seams..
Not convenient.

**Comment by davidrenne** [comment]
Im good, i got my PS3 controller

Thanks for looking into it.
