### ISSUE TITLE
Feature Request: Controller Configuration on First Use

### ISSUE THREAD

**Issue by chane2k1** [libretro/ludo#260]
I purchased a Retro-bit Saturn controller and Ludo and Lakka recognize it as SWITCH SNES controller and with that mapping i can't navigate in menus. The controller does have an x-input mode, but is a hassle to switch on every time. I can use a keyboard with Lakka navigate and rebind, but this is not currently a possibility with Ludo. It would be nice if Ludo had a controller configuration wizard similar to RetroPie on first use of the device or a rebind menu I could access with a keyboard.

**Comment by johnnyq** [comment]
Controllers should be automapped I believe this is being worked on

**Comment by kivutar** [comment]
@chane2k1 I think this issue should be moved to Lakka (or even better, RetroArch) issue tracker.

I'm sorry that your controller is not supported by RetroArch yet. I propose that you go with them through the commands to check the device name, the vendor ID and product ID of your pad, and find why the wrong autoconfig is chosen.

Some joypad manufacturer have the bad practice of using vid:pid of well known joypads with a totally different mapping... if it's the case of yours, there is no chance that autoconfig will work one day. And so far Ludo is autoconfig only.
