### ISSUE TITLE
Feature Request: Rewind Support

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#262]
I have been using this feature on NES and SNES platform for Nintendo Switch and I love it, its designed extremely well and makes some of the older game much more enjoyable, any chance on implementing something similar in Ludo? This would be a major plus I never thought I would like it but playing ninja gaiden with rewind has been a pleasure

**Comment by kivutar** [comment]
Does it imply mapping rewind to some keys on the joypad?

**Comment by johnnyq** [comment]
absolutely, maybe pressing the home button and then have an option to rewind when selected it could show screenshots of the last 15 frames at the bottom and one can be selected to go back. Something along those lines.

**Comment by kivutar** [comment]
I like the UI idea, but I prefer to postpone such features because it makes more sense to first build a strong base.

**Comment by johnnyq** [comment]
I agree

**Comment by kivutar** [comment]
I close this for now as we are still struggling 1 year later with foundational issues, not a priority

**Comment by johnnyq** [comment]
I know this is closed but I figure we could maybe revisit the rewind feature since the base has been pretty solid/stable
