### ISSUE TITLE
Debian / Ubuntu packaging

### ISSUE THREAD

**Issue by kivutar** [libretro/ludo#276]

**Comment by ItzSwirlz** [comment]
I'm in charge of the ubuntu Cinnamon Remix and @flexiondotorg was interested in this. I'll def be happy to do this but I'm having some build issues and running stuff

**Comment by ItzSwirlz** [comment]
So retroarch and games packaging in Debian is here:

https://salsa.debian.org/games-team

So I'm going to subscribe to their mailing list, email them, and depending on that I'll open a RFP/ITP (Request for packaging)/(Intent to package)

**Comment by kivutar** [comment]
Maybe the most difficult part will be that Debian policies prevent to pack the .so in the same package as the executable. And one of the principles of Ludo is to come with his own cores, at a fixed version, on a release basis.
