### ISSUE TITLE
Feature Request: 8bitdo SFC30 and SNES30 auto button mapping support

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#288]
I have two 8bit controllers (SFC30 and SNES30) that work in Lakka but not in Ludo. They detect but buttons are not mapped. Also is there a way to map the buttons manually through ssh.

**Comment by kivutar** [comment]
Currently the mappings are hardcoded in Ludo. So you would have to know how to compile Ludo on the 3 supported OSes to add support for these controllers.

We already support the  NES30 Pro so I'm not against adding more of the 8bitdo familly, as long as:

 - I own them
 - Somebody who owns them engage in supporting them on the long term

I do own a SNES30, I think, so we can start adding support for this one.

**Comment by johnnyq** [comment]
that sounds good, the SFC30 is the same button layout and control style as the SNES30 except they use different colors for Y X B A while the SNES30 they use purple color Y X B A

**Comment by kivutar** [comment]
@johnnyq can you confirm that the detected name of the SNES30 is `SNES30 Joystick` on the 3 OS?
You can do this by running Ludo and plugging the pad, the name should appear in the notification.

**Comment by johnnyq** [comment]
I attached the screenshot of what it says when I plug it in, also i took a pic of the controller

![2019-11-21 22-45-23-1](https://user-images.githubusercontent.com/1812594/69396615-d8d77e00-0cb0-11ea-8a3d-785972c20c2f.JPG)
![2019-11-21 22-45-23-2](https://user-images.githubusercontent.com/1812594/69396616-d8d77e00-0cb0-11ea-9476-27398d0a8de3.JPG)

**Comment by kivutar** [comment]
I'm going to need the exact strings, because I can't really guess the number of spaces.
Except these information for the SNES30, the pull request is ready.

**Comment by johnnyq** [comment]
let me see if I can get an exact string from you from the command line

**Comment by johnnyq** [comment]
Here i pulled this straight from dmesg

```
[   99.282140] usb 1-1.2: Product: SNES30 Joy    
[   99.282147] usb 1-1.2: Manufacturer: SNES30            
[   99.285714] input: SNES30             SNES30 Joy     as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2/1-1.2:1.0/0003:2DC8:AB20.0002/input/input1
[   99.286195] hid-generic 0003:2DC8:AB20.0002: input,hidraw0: USB HID v1.10 Joystick [SNES30             SNES30 Joy    ] on usb-3f980000.usb-1.2/input0

```

**Comment by kivutar** [comment]
Thanks, I added it for Linux, now I'll need the same for window and mac.

**Comment by johnnyq** [comment]
Excellent looking forward to it!

**Comment by kivutar** [comment]
Is this fixed now?

**Comment by johnnyq** [comment]
@kivutar Absolutely just tested both controllers they work great this can be closed
