### ISSUE TITLE
Feature Request: GGPO Netplay

### ISSUE THREAD

**Issue by fabricioanciaes** [libretro/ludo#290]
GGPO netcode is open source now, ludo would greatly benefit from this.

This makes a good feature for this emulator since its pretty user friendly, rollback netcode is super important and I can see a bunch of communities based around older games taking advantage of this feature, it would be definitely a game changer.

The general idea of rollback netcode is resuming execution while you wait for inputs (because of latency) and then, when said inputs are received, rollback to that point in time where the inputs were made, fast forward, and patch the new state in the game again. Similar to retroarch's run ahead feature. Maybe using a second instance to do rollbacks could be a good idea.

More info on GGPO: https://www.ggpo.net/

**Comment by kivutar** [comment]
This kind of netplay is nice but very difficult to implement. Here are the issues we faced when implementing such thing in RetroArch. In addition to the more general difficulties of implementing netplay.

 - Unportable savestates (they can be endianess dependant, making cross platform rollback impossible)
 - ROM missmatch (there are many version of the same ROM and they don't behave the same)
 - Indeterministic emulators (the random function returning different results on both machines)
 - NAT traversal (it makes any p2p app a pain to implement anyway)
 - Security (meeting endpoint was spammed with racist room names)

So I don't think we're going to add netplay to Ludo anytime soon. Out current goal is to make game playables, and we've not even there yet, as 3d cores are still crashing.

**Comment by johnnyq** [comment]
Agreed, I think getting 3D cores is a much higher priority.

**Comment by kivutar** [comment]
I got this working on a separate repo, but it's honestly too much complexity for Ludo..
I would clearly not have the time to make this work for all systems, for 2+ players, and make it robust.
It also mean maintaining a matchmaking system, which mean servers, and maintaining a server.
