### ISSUE TITLE
Games with vertical orientation are not rotated

### ISSUE THREAD

**Issue by ImJezze** [libretro/ludo#292]
I just tested 1941 with the FB Alpha core and this was the result.

![grafik](https://user-images.githubusercontent.com/11963815/69479953-83f84c80-0e03-11ea-8bfc-135019d9109f.png)

**Comment by kivutar** [comment]
Good catch, this one should be fixable easily. I'll give it a try soon.

**Comment by ImJezze** [comment]
I've tested v0.10.3 and the issue is not completely fixed. The initial state seems to be wrong. I need to enable and disable the vertical mode in the options before the game is rotated correctly.
