### ISSUE TITLE
Compiling on Windows with Msys2

### ISSUE THREAD

**Issue by ImJezze** [libretro/ludo#293]
This is not a real issue, it's more like a reminder for other people who also try to build Ludo on Windows with Msys2. The good thing is it works, but I had to overcome some obstacles. And maybe someone has addition hints to fix the remaining minor issues.

1. I installed the base package of Msys2, go and openal
    msys2-x86_64-20190524.exe
    \> pacman -S mingw-w64-x86_64-go
    \> pacman -S mingw-w64-x86_64-openal
2. I cloned the repository
    \> git clone --recursive https://github.com/libretro/ludo.git
3. And tried to build Ludo
    \> go build
    >go: downloading ...
    >go: downloading golang.org/x/mobile v0.0.0-20190607214518-6fa95d984e88
    >go: downloading ...
    >\# golang.org/x/mobile/exp/audio/al
    >E:/Development/Compiler/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lOpenAL32
    >E:/Development/Compiler/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lOpenAL32
4. I had to changed -lOpenAL32 to -lopenal in al_notandroid.go and alc_notandroid.go in the downloaded golang.org/x/mobile package
5. I tried to build Ludo again, this time with success

After the build, there are still two minor issues.
1. The compiled ludo.exe has no icon (or more precise the default one)
2. And I had to rename OpenAL32.dll to libopenal-1.dll

**Comment by kivutar** [comment]
Interesting. I didn't know Msys2.

For the windows icon, see the Makefile, where the icon is applied after the compilation.

Do you have any idea why they are doing this? https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-openal/0003-openal-not-32.mingw.patch

**Comment by ImJezze** [comment]
I'm not sure, probably because the OpenAL package for Mingw-w64 is actually not 32-bit, but 64-bit. And that patch seems to be the reason why I had to change link-command.

**Comment by kivutar** [comment]
It's also `-lopenal` on Linux distros, so I think that somehow Msys2 is more of a posix platform.
