### ISSUE TITLE
8bitdo snes30 sfc30 - Home Button combo

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#295]
Hey @kivutar The snes30 and sfc both work great altough i forgot to mention the home hotkey, maybe we can make it start and select at the same time. Let me know what you think.

**Comment by kivutar** [comment]
We would need to make this configurable, because in some games, Start+Select already does something.

**Comment by johnnyq** [comment]
maybe even hold start for 3 secs would be a good hot key

**Comment by johnnyq** [comment]
I think for now Down L R and Y would work

**Comment by johnnyq** [comment]
how about down select by default instead, its whats used in the nes and snes classic and makes sense and its simple

**Comment by kivutar** [comment]
I've created a broader issue here https://github.com/libretro/ludo/issues/new
