### ISSUE TITLE
Feature request: Run-Ahead to reduce lag 

### ISSUE THREAD

**Issue by alessioscand** [libretro/ludo#297]
Hi!
it would be nice if ludo (and LudOS) would support the Libretro "Run-Ahead" feature:
https://docs.libretro.com/guides/runahead/

(It works very well even on a Raspberry Pi 4).

Thank you!

**Comment by kivutar** [comment]
Run-ahead is of course a very nice feature to have but sorry, too complex for Ludo, it's not in our design goal.
