### ISSUE TITLE
Initial orientation is not set

### ISSUE THREAD

**Issue by ImJezze** [libretro/ludo#299]
In #294 you implemented the handling of the libretro.EnvironmentSetRotation event to fix #292. However it seems this event is not fired when the game is loaded, only when you change the related option (e.g. vertical mode). This maybe is a bug of the core itself, I don't know. Anyways, I tried to figure out how to request the initial rotation from the core, to set is manually when the game is loaded. But I'm not that familiar with the API, maybe you know how to.

**Comment by kivutar** [comment]
I think that it works like the video info. The core will start with sending wrong information, and during the first frames of the game, will call the environment callback to update the frontend with the right information.

It's clunky but it's how the API works (I think).

Did you notice any issue with this feature? For me it works out of the box on FBNeo games. I've not tried with MAME yet.

**Comment by ImJezze** [comment]
Unfortunately, it does not work out of the box for me. I tested v0.10.3 on Windows with the FBNeo core, started 1941 and the game was not rotated. I had to toggle the vertical mode option of the core on and off again to get the correct rotation.

I haven't attached a debug yet, but my guess is that the callback for EnvironmentSetRotation is not called when the game starts. And therefore the initial rotation is never set unless you change the related option of the core.

**Comment by kivutar** [comment]
For me without touching anything:

<img width="1072" alt="Screen Shot 2019-12-09 at 08 59 46" src="https://user-images.githubusercontent.com/442722/70401472-4d0c7280-1a62-11ea-927a-aa8283d9de81.png">

Maybe the shader? I'll have to try different combinations of options.

**Comment by ImJezze** [comment]
I'll try to debug it, maybe the problem is really the core of FBNeo for Windows and the callback is not received on game start.

**Comment by ImJezze** [comment]
I had some time to debug this issue and logged the environment callbacks.

The following is only the interesting part of the log.

> [MINGW64] E:\...\ludo.exe -v
> 2019/12/22 14:31:49 [Video]: OpenGL version: 4.5.13399 Compatibility Profile Context 15.201.1151.1008
> 2019/12/22 14:31:54 [Core]: Name: FinalBurn Neo
> 2019/12/22 14:31:54 [Core]: Version: v0.2.97.44 d454549
> 2019/12/22 14:31:54 [INFO]: [FBNEO] Archive: 1941
> 2019/12/22 14:31:54 [INFO]: [Cheevos] System RAM set to 0000000005A8EEC0 65536
> 2019/12/22 14:31:54 [Env]: EnvironmentSetRotation
> 2019/12/22 14:31:54 vid.SetRotation(81604378625)
> 2019/12/22 14:31:54 [INFO]: Driver 1941 was successfully started
> 2019/12/22 14:31:54 [Core]: Game loaded: E:\...\1941.zip
> 2019/12/22 14:32:00 [Env]: EnvironmentSetRotation
> 2019/12/22 14:32:00 vid.SetRotation(0)
> 2019/12/22 14:32:02 [Env]: EnvironmentSetRotation
> 2019/12/22 14:32:02 vid.SetRotation(1)

There are three calls of EnvironmentSetRotation:
1. with 81604378625, the initial state
2. with 0, when I manually set "vertical mode" option to enable
3. with 1, when I manually set "vertical mode" option to disable

So, 1 should be the correct initial state, but it seems to be messed up somehow.

What's also interesting is that, when I load Alien Vs Predator - which has normal landscape orientation - the initial state 0 is send. When I load 1941 again - without closing the Ludo - the initial state 1 is send.

It might be a coincident, but 81604378625 modulo 4 is 1 again. This probably could be used as a "dirty" fix.

**Comment by kivutar** [comment]
The one that counts is the last call, because it's what sets the orientation in the end, no?

**Comment by ImJezze** [comment]
Sure the last call counts. But the 2nd and 3rd call are triggered by changing the core's settings manually. Without me changing the "vertical mode" option the initial send state 81604378625 will be applied, which is not valid and therefore no rotation.

**Comment by kivutar** [comment]
There is something wrong indeed.

Take a look at here: https://github.com/libretro/FBNeo/blob/master/src/burner/libretro/libretro.cpp#L737-L750

orientation can only be 0, 1, 2, or 3 according to the code. I wonder how we can get a 81604378625

**Comment by ImJezze** [comment]
Yeah, it's really strange! And I don't know why it only occurs on Windows. Maybe I should file a bug report in the core repository.

I know this is not a real fix for the problem, but #301 at least ensures a valid value in the range of 0 and 3.
