### ISSUE TITLE
Respect the XDG base directory specification on Linux 

### ISSUE THREAD

**Issue by pdureau** [libretro/ludo#302]
The files in `.ludo` should be relocated to the appropriate locations specified by the [XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (e.g. config files go in `~/.config/ludo/`, "cahe files go in `~/.cache/ludo/` and data files go in `~/.local/share/ludo`) on Linux.

Reasons:
* It makes it easier to synchronize dotfiles across multiple devices.
* One fewer dotfile in the home directory.
* Makes it easier to find the configuration files for new users (search in the standard location `~/.config/` instead of having to look it up online or run `find / -name '*ludo*'`)
* This standard is supported by many Linux programs and tools (e.g. Python, LibreOffice, NeoVim).
* ...

There is already at least a go language implementation of this specification: https://github.com/adrg/xdg which also manage  macOS & Windows.

**Comment by kivutar** [comment]
Thanks, will look into this.

**Comment by pdureau** [comment]
It looks like this PR is related to the current issue: https://github.com/libretro/ludo/pull/307 doesn't it?

**Comment by kivutar** [comment]
No they are 2 different things. This PR honors the $HOME env var and nothing more
