### ISSUE TITLE
Overwrite or Delete Saves?

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#304]
Is there any current way to overwrite or delete saves states?

**Comment by kivutar** [comment]
No, but I'm OK to add a way to delete saves, with a confirmation message.

**Comment by johnnyq** [comment]
Maybe when you hit save have it display 4 slots and they can select the slot similar to NES classic

**Comment by kivutar** [comment]
I prefer not to limit the number of saves to 4 to be able to synchronize them easily across devices without having conflict management. Having them timestamped really prevent any state loss.

**Comment by johnnyq** [comment]
I totally agree @kivutar 
sometimes the timestamps are off if the pi is not hooked up to the internet to sync the time maybe a consecutive order like save 1 save 2 save 3 and so on

**Comment by johnnyq** [comment]
For Deletion When you access Save States then highlight one of the load states an additional key option should appear on the bottom hint screen for Delete using another assigned controller button.

**Comment by johnnyq** [comment]
or even maybe if you highlight a Load State press the right Dpad or arrow and a big red delete button will appear kind of like in IOS apple mail if you swipe left a big red delete button appears. Then they have button hint will show delete instead of Load if the press left Dpad arrow it will cancel the delete
