### ISSUE TITLE
New NES Game What Remains

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#305]
A new but really good NES game got released for free called what remains would you be able to add this so it scans in properly to the playlist

here is a link

https://iodinedynamics.com/whatremains.html

**Comment by kivutar** [comment]
Yes we need to start populating the new homebrew folder in libretro db

**Comment by johnnyq** [comment]
excellent! Thanks

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-database/pull/986

**Comment by johnnyq** [comment]
@RobLoach Thanks for adding

**Comment by johnnyq** [comment]
looks like it has been added to libretro but not ludo yet, just tested this.

**Comment by RobLoach** [comment]
Correct. The database currently uses [kivutar's ludo-database repo](https://github.com/kivutar/ludo-database), by design. Has less entries. Worth testing ludo with the libretro one.

**Comment by kivutar** [comment]
I regularly update mine using the ones of libretro, but the difference is that I test them manually to check if it creates wrong entries, if it creates duplicate entries, if turbografx roms end up in the supergraphx playlist, and other usual bugs.

The rdb in libretro are not tested enough IMO. And sometimes, the FBA rdb gets updated while I've not yet updated the FBA core, which creates problems.

So for the sake of integration, I have to keep a clone.

**Comment by kivutar** [comment]
I switched to the latest xml dats from no-intro. Please try to rescan.
