### ISSUE TITLE
I have a problem with the menu image.

### ISSUE THREAD

**Issue by lvitals** [libretro/ludo#315]
I have a problem with the menu image. It is showing black borders. I run on a Linux distribution with Wayland and an Intel video adapter. What is causing this?

![image](https://user-images.githubusercontent.com/2145794/75728164-cb755b00-5cc5-11ea-9ab7-4b130cacf710.png)

**Comment by kivutar** [comment]
It can be the driver. Maybe we're doing something wrong in our shaders too.
I will have to try this in wayland. I have a i915 card too.

**Comment by kivutar** [comment]
I close this for now as I clearly have no idea how to fix this and it's been a year.
