### ISSUE TITLE
Dualshock 3 analog inputs

### ISSUE THREAD

**Issue by CoffeeNite** [libretro/ludo#317]
While playing an SNES game, the Dualshock 3 does not recognize any analog inputs which I assume is by design, however it appears to start randomly mapping inputs when I press L3 or R3 or a combination.  I tested this in Aero the Acrobat for SNES.  Aero would start moving right and occasionally crouch while trying to press L3 or R3.

**Comment by kivutar** [comment]
Related to https://github.com/libretro/ludo/issues/350
