### ISSUE TITLE
Is coreGetTimeUsec returning epoch nanoseconds intentional?

### ISSUE THREAD

**Issue by 1lann** [libretro/ludo#319]
Hey so I'm developing a front-end that makes use of ludo's libretro Go bindings, and when looking at the usage of `BindPerfCallback` in ludo's `environment.go`:
https://github.com/libretro/ludo/blob/f981cb5e855bedfd8a52018fe4217909d72b1b47/core/environment.go#L28-L31
I noticed that the current UNIX time in nanoseconds is being returned, despite the fact that the function is called `getTimeUsec` which would imply microseconds, and I can't seem to find any evidence of the number being eventually converted to microseconds when it is provided to libretro. libretro.h even specifies that this number should be in microseconds. Is this intentional?

**Comment by kivutar** [comment]
It's not intentional, this code is wrong I think.

**Comment by 1lann** [comment]
@kivutar eek btw it should be / 1000 not * 1000.
