### ISSUE TITLE
Different Background images for each game while you're browsing

### ISSUE THREAD

**Issue by fmaida** [libretro/ludo#320]
I know that you said you want to keep ludo source code as much clean and simple as possible, so feel free to discard this suggestion if you don't like it of course.

I was thinking this: when you are browsing games, instead of having a black background behind the GUI, could you show the screenshot of the currently selected game, enlarged to fit the screen and slightly blurred?

I have made a mock-up image to explain visually this idea. On the upper side you can see how a game is currently displayed under Ludo 0.11, and on the bottom there's a my mock-up image:

![0](https://user-images.githubusercontent.com/605017/80824189-39fb6a00-8bde-11ea-9d1a-b4320a63354c.jpg)

![1](https://user-images.githubusercontent.com/605017/80942646-9aa8c380-8de5-11ea-84fb-ff8ac030cbe2.jpg)

Each time you choose a different game from the menu, a different background image would be displayed.

I don't know if you might like this idea or even if it's too complicated to implement, so as I wrote feel free to reject it.

**Comment by johnnyq** [comment]
Woah I like this!!! nice work @fmaida

**Comment by kivutar** [comment]
I've always liked this idea. For now Ludo doesn't have support for multi pass shaders.
Is there a blur shader that is single pass and not too heavy?
