### ISSUE TITLE
Remembering When

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#323]
When Lakka used to look like this 

[https://web.archive.org/web/20160320052553im_/http://www.lakka.tv/videos/menump4.mp4](https://web.archive.org/web/20160320052553im_/http://www.lakka.tv/videos/menump4.mp4)

The simplicity and the amazing theme can we bring the icon theme to Ludo!

**Comment by johnnyq** [comment]
going through the lakka news it looks like the old lakka was written in c before they moved over to XMB. I think  Ludo project is mimicking the older lakka which brings the simplicity back.

**Comment by kivutar** [comment]
These icons are still there https://github.com/libretro/retroarch-assets/tree/master/xmb/flatui/png

If you want to make a theme, you can replace the PNGs in the assets folder of ludo.

The menu of Lakka has first been prototyped in lua+love2d, then ported to C to be included in RetroArch and renamed XMB.

**Comment by kivutar** [comment]
I close this since I don't have immediate plans to support icon themes switching, but the functionality is still achievable by simply replacing the files.
