### ISSUE TITLE
Raspberry Pi 4 8GB not loading fresh image

### ISSUE THREAD

**Issue by birdybro** [libretro/ludo#331]
https://github.com/libretro/LudOS/releases/download/v1.0-alpha30/LudOS-RPi4.arm-1.0-alpha30.img.gz - Version image I'm using.

Getting error message in attached screenshot.

![IMG_20200730_101253](https://user-images.githubusercontent.com/16388068/88947150-5fcff380-d24d-11ea-8248-37bbef21940b.jpg)

The boot partition has the following.

![image](https://user-images.githubusercontent.com/16388068/88947355-aaea0680-d24d-11ea-9d24-6d3aadeabe20.png)

When installing a regular Raspberry Pi OS of the newest version from the raspberry pi imager:

![image](https://user-images.githubusercontent.com/16388068/88948499-3c0dad00-d24f-11ea-8403-b86db876634b.png)

The files in the boot partition are significantly different. This is also very different from what I remember them being like back when it was called "Raspbian" even for pi4 versions, so something must have changed recently for the 8GB edition.

It's possible that newer revisions of the firmware on the raspberry pi 4 model do not support the older method used for LudOS's boot partition. Just a guess though.

EDIT: my firmware version is up to date, just confirmed:

```
pi@lilypi4-8gb:~ $ sudo rpi-eeprom-update
BCM2711 detected
VL805 firmware in bootloader EEPROM
BOOTLOADER: up-to-date
CURRENT: Thu 16 Apr 2020 05:11:26 PM UTC (1587057086)
 LATEST: Thu 16 Apr 2020 05:11:26 PM UTC (1587057086)
 FW DIR: /lib/firmware/raspberrypi/bootloader/critical
VL805: up-to-date
CURRENT: 000137ad
 LATEST: 000137ad
```

**Comment by kivutar** [comment]
Hi, LudOS is made to be flashed with `Etcher` or `dd` on the SD card. Not copied on the filesystem of the SD card.

**Comment by birdybro** [comment]
I didn't copy it there I used the raspberry pi imager. I will use etcher instead later and try again, thanks.

**Comment by birdybro** [comment]
Imaged the SD card with Etcher this time, newest version of etcher and redownloaded newest rpi4 Ludos image just to be sure.

![image](https://user-images.githubusercontent.com/16388068/89107124-12d65380-d3ec-11ea-842a-9ec3be3c72a5.png)

Same exact files on the boot partition.

![IMG_20200801_114319](https://user-images.githubusercontent.com/16388068/89107155-487b3c80-d3ec-11ea-9bdc-d02e507dbac7.jpg)

Same exact error.

**Comment by birdybro** [comment]
Comparing files...

https://drive.google.com/file/d/1E79KQi0p7AjVdQO_46MiPc5RgSR-Y2ln/view?usp=sharing - 0.zip, boot partition files from newest raspberry pi os

https://drive.google.com/file/d/1hTjdNkQHtqgJox_lsRx1uPnKlsCgFSCE/view?usp=sharing - D.zip, boot partition files from newest LudOS pi4 image, sans "SYSTEM" because it's very large.

The files mentioned int he error message are recover4.elf, recovery.elf, and start4.elf. Additionally the hash for start.elf is not compatible with the pi4 8gb default firmware (which is newer).

When transferring just the new start.elf so as to get past the failed hash check... I get the exact same error.

https://github.com/raspberrypi/firmware/commits/master

I am now noticing this is potentially solved in alpha32.

https://github.com/libretro/LudOS/commit/1c135e5303ae599339eea56fd6c253dd81965674

The website download is on alpha30 of LudOS so it needs to be updated or else any RPi with firmware from the last few months will not work.

I will test alpha32 to see if that works.

**Comment by birdybro** [comment]
https://github.com/libretro/LudOS/releases/download/v1.0-alpha32/LudOS-RPi4.arm-1.0-alpha32.img.gz

Confirmed Alpha32 solves the issue. Alpha30 is the current download link on RPi4 and the solution is for the link to be updated to Alpha32 so others don't have this problem in the future.

Closing as it's resolved.
