### ISSUE TITLE
8Bitdo NES30 Pro plugged but not configured

### ISSUE THREAD

**Issue by flexiondotorg** [libretro/ludo#332]
I'm using Ludo 0.11.2 on Ubuntu 20.04 (amd64) with an 8Bitdo NES30 Pro connected via USB, which I believe is a supported configuration. However, Ludo reports:

```
2020/08/01 00:33:13 [Input]: Joystick #0 unplugged.
2020/08/01 00:33:30 [Input]: Joystick #0 plugged: 8Bitdo NES30 Pro but not configured.
```

The gamepad responds to all controller inputs using `jstest`. Here's the output from `dmesg` when the controller is connected:

```
[310598.375479] usb 1-4.1.4: Product: 8Bitdo NES30 Pro
[310598.375480] usb 1-4.1.4: Manufacturer: 8Bitdo NES30 Pro  
[310598.381636] input: 8Bitdo NES30 Pro   8Bitdo NES30 Pro as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4.1/1-4.1.4/1-4.1.4:1.0/0003:2DC8:9001.0028/input/input55
[310598.381715] hid-generic 0003:2DC8:9001.0028: input,hidraw9: USB HID v1.11 Gamepad [8Bitdo NES30 Pro   8Bitdo NES30 Pro] on usb-0000:00:14.0-4.1.4/input0
```

Keen to help resolve this as I have other 8Bitdo controllers discussed in other issues that I'd be interested in adding and maintaining support for.

**Comment by kivutar** [comment]
Maybe the kernel changed the name from `8Bitdo NES30 Pro   8Bitdo NES30 Pro` to simply `8Bitdo NES30 Pro`.
Or maybe it's the switch to the new version of GLFW.

We would need to change this line to check https://github.com/libretro/ludo/blob/5faca1d591e30b512e939f9347a82c1e2a7db346/input/binds_linux.go#L12

**Comment by MikaXII** [comment]
Well I do nothing and it doesn't work anymore...

**Comment by MikaXII** [comment]
First time work fine.
I've install fwupd to upgrade the firmware, no update available but after this unable to use my controller 8bitdo
I try to launch it in root (for testing) and the controller event was triggered but not working
I removed fwupd and all his dependencies and it work great again.

**Comment by kivutar** [comment]
Should we close this then? I'm not sure.

**Comment by kivutar** [comment]
This should be fixed now, please reopen if it's not working on the latest release.
