### ISSUE TITLE
Freeze then crash when trying to browse above the root directory

### ISSUE THREAD

**Issue by vgf89** [libretro/ludo#338]
On Windows 10, if you go to any file browser in ludo (i.e. Main Menu -> Load Game) then click ".." repeatedly until you are in the root directory of the drive, then click ".." one more time, Ludo freezes then crashes.

Instead of crashing, it should show the connected drives (C:, D:, etc) and allow me to browse them.

I'm running Ludo-Windows-x86_64-0.11.2

**Comment by kivutar** [comment]
Fixed
