### ISSUE TITLE
PSX core cannot find BIOS?

### ISSUE THREAD

**Issue by sunnystormy** [libretro/ludo#341]
Hello! I love the project! I'm currently using Ludo as my daily (emulation) driver, and am very happy with it.

I'm unable to run any PSX games, though, b/c the PSX core doesn't know how to find the BIOS? I know I have a copy on my system, but is there a specific directory I need to drop it into so Ludo knows where it is?

Thank you for your help!

**Comment by kivutar** [comment]
Yep, in the `system` directory, just like for RetroArch

**Comment by WilliamVercken** [comment]
I don't understand why this is not written in the documentation... Or maybe I missed something somewhere ?

**Comment by kivutar** [comment]
For now only the differences with RetroArch have been documented. For all the other things, you can directly refer to the libretro wiki and it will apply.
