### ISSUE TITLE
PI4: XBOX 360 with Wireless USB-Connector and 8BitDo SN Pro do not work

### ISSUE THREAD

**Issue by mtoensing** [libretro/ludo#348]
Hi, 

 I tried Ludo on macOS Catalina and it worked fine. I love the idea of ludo. Great UI, great speed and decisions instead of asking the user. I flashed a version for my Pi4 with 4GB Ram. Sadly neither the 8BitDo SN Pro (wired with USB to USB-C) nor the XBOX 360 wireless USB-Adapter work. They are shown correctly at the top but I can not use the menu. I tried restarting the system with the controllers connected and changed the order of joypads but no luck. Any idea? I would love to use this on my pi. 

relates to #223

**Comment by johnnyq** [comment]
Hi @mtoensing I have a raspberry pi 4and the 8bitdo sn pro controller latest firmware and ludos installed Try this press start and x at the same time to turn on your 8bit do controller.

**Comment by mtoensing** [comment]
Okay, mystery solved: 

8bitdo SN30 Pro: works (looks like the us version)
8bitdo SF30 Pro: does not work (look like the pal version)

I own both but only the SN works.

**Comment by kivutar** [comment]
Bluetooth should work, but XBOX 360 wireless USB Adapter doesn't use the regular bluetooth, it's either Infra Red, or a proprietary bluetooth. I know we can make it work because we made it work on Lakka.

It's certainly just the button bindings missing in the source code of Ludo. For both controllers.

**Comment by kivutar** [comment]
I've created two separate issues so we can start tackling these

**Comment by aptonline** [comment]
I have the standard SF30 GamePad which doesn't seem to be detected in Ludo but is connected to my Mac and works perfectly in Retroarch.  Should I be seeing setting for the GamePad in the top level setting menu?
