### ISSUE TITLE
Add support for 8bitdo SF30 Pro controller

### ISSUE THREAD

**Issue by kivutar** [libretro/ludo#352]
Related to https://github.com/libretro/ludo/issues/348

 - [ ] Windows
 - [ ] OSX
 - [ ] Linux
 - [ ] LudOS

**Comment by aptonline** [comment]
I have the standard SF30 GamePad which doesn't seem to be detected in Ludo but is connected to my Mac and works perfectly in Retroarch. Should I be seeing setting for the GamePad in the top level setting menu?

**Comment by johnnyq** [comment]
It should work in xbox mode 
- make sure controller is off or turn the contoller off by holding start until there is no light.
- Press start and X to turn the controller on which will put it into xbox mode. (Note it will keep it in the mode the next time you turn it on, unless you change the mode again)

**Comment by aptonline** [comment]
Thats doesn't seem to work for me, I have removed my previous bluetooth connection and attempted to pair using the Xbox method and the controller doesn't show for pairing, so I then paired again via bluetooth, turned off the controller (as you recommended) and started it in Xbox mode but the controller next connects.  As mentioned I can connect fine using bluetooth and every other emulator app detects the controller and works fine (RetroArch, OpenEMU etc) but Ludo doesn't detect it.

**Comment by kivutar** [comment]
Now that we switched to GLFW mappings, it should work.
If not, it became an upstream issue and the bug should be declared at glfw.
