### ISSUE TITLE
Trigger menu combo

### ISSUE THREAD

**Issue by kivutar** [libretro/ludo#353]
Let's consider:

 - L3+R3 (easy to remember, works on pads that have analog sticks)
 - Down+Select (works on SNES controllers, used on SNES classic)
 - Down+Start (works on Genesis controllers)

Other possibilities: long presses?

**Comment by johnnyq** [comment]
this looks perfect to me, lets leave the long presses out of it, as I like to save state alot and holding the buttons down could get annoying over time.

**Comment by johnnyq** [comment]
I see you added R3 and L3 but what about the lonely snes controllers can we add the down select for them as well?
