### ISSUE TITLE
Bug: Bootscreen Graphic not showing on Raspberry pi 3b+

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#354]
Boot screen Graphic not showing on Raspberry pi 3b+ I can verify it is showing on Raspberry Pi 4 during boot though

**Comment by kivutar** [comment]
Indeed, this bug has been there for a while and I have no idea how to fix it.

The RPi3 and RPi4 are supposed to be compatible enough to not have this kind of differences.

**Comment by johnnyq** [comment]
sounds like it might be an upstream issue with libreELECT, have you thought maybe switching the underlying OS to something else like Ubuntu or Armbian. It seems like LibreELECT has become stale.

**Comment by kivutar** [comment]
This might be fixed now, it is fixed for me at least, but I changed my TV so I'm not sure if it's fixed for everybody

**Comment by johnnyq** [comment]
@kivutar I can confirm this is fixed =]

**Comment by johnnyq** [comment]
@kivutar I made a mistake when I made my last comment.

It was working for the Raspberry Pi 4 and not the 3b+ 

I have switched to using my 3b+ and noticed the boot graphic still doesn't display during boot.
