### ISSUE TITLE
Feature Request: Load Game should initiate in /storage/roms directory instead of /storage

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#356]
Load Game should initiate in /storage/roms directory instead of /storage

**Comment by johnnyq** [comment]
maybe just on Ludos since roms can be stored elsewhere if running on a PC OS like windows, linux desktop or mac os

**Comment by kivutar** [comment]
On Ludo there is a reason why we start on ~: as you said, ROMs can be anywhere

On LudOS it is also the case, if you plug an additional block storage device, it will be mounted in /media
Same when you boot live on a machine that have an internal hard drive.

So I think it's better to keep it this way.
