### ISSUE TITLE
Request: Removal of some settings items

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#358]
- Video Monitor Index (I'm not sure what this is for exactly)
- Audio Volume (Can be controlled at the source TV volume, computer volume, etc) Although I really like those slider graphics maybe they can be used elsewhere.
- Menu Audio Volume (Its a pleasant sound choice and its at a perfect default level i'm sure this can be removed as well)
- Show hidden Files, SSH, Samba, Bluetooth maybe put into an advanced submenu under settings.

This is to keep up with minimalist, best defaults out of the box approach Ludo provides

**Comment by kivutar** [comment]
Video Monitor Index is when you have 2 monitors plugged, and you want to select on which one Ludo should be when it is full screen.

Maybe Show Hidden Files should always be ON?

I don't plan to implement submenus yet, it makes the code way more complex.

**Comment by johnnyq** [comment]
- I see, Video monitor makes sense when running on a PC. Could it auto detect if two monitors exist then show the option?

- Your right maybe we don't even need hidden files option to be present, but leave it so it doesn't display hidden files by default. I can't really see a reason to show hidden files anyway unless someone puts roms in a directory .roms which wouldn't make much sense. hidden files and directories seems more like a Retroarch thing than a Ludo thing, hence Ludo being minimal and simple.
- Got ya i'm all for simple code so no sub menus
- What about removing audio volume and menu volume? is it even necessary since the volume can be controller via the OS or the output sound device itself.

**Comment by kivutar** [comment]
Showing hidden files is needed in the case of pointing to /home/foo/.ludo/system for example

Being able to lower the volume on PC is useful, if you're using the audio for something else, like a video conference.
