### ISSUE TITLE
Feature Request: Screensaver Random Game gets selected and played after idle

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#361]
This would be a neat feature similar how the NES classic and SNES classic do it. 

- Basically after 3 minutes of inactivity on the main screen (no game is loaded) a random game gets selected started.
- then after 3 minutess it selects another random game and so on. 
- When you hit a button it stops the screensaver and returns you back to the main ludo screen.

**Comment by kivutar** [comment]
Sorry, way too heavy to implement, so it's out of scope
