### ISSUE TITLE
Add Games - Missing Games

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#366]
This is a list of games that I have that are not being detected via scan. Is my naming wrong or are these games just not in the DB yet?
### NES

- Bucky O'Hare (U) [!].zip
- Contra Force (U).zip
- Deja Vu (U).zip
- Duck Tales 2 (U).zip
- Faxanadu (U).zip
- Gradius 2 (J).zip
- Metal Gear (U).zip
- Pokemon Yellow.nes
- Startropics 2 - Zoda's Revenge (U).nes
- whatremains-1.02.nes

### SNES

- Super Metroid Redesign.sfc
- Chrono Trigger - Crimson Echoes.smc

### Playstation

- Resident Evil 2 (USA) (Disc 1).cue
- Chrono Cross (USA) (Disc 1).cue
- Final Fantasy VII (USA) (Disc 1).cue
- Mega Man X4.cue
- Castlevania - Symphony of the Night (USA).cue

**Comment by kivutar** [comment]
From what I see your NES and SNES roms are not No-Intro so the checksum might not be right.

For the PlayStation roms, it might be fixed now, can you rescan?

**Comment by kivutar** [comment]
We will treat this as external issues. Games will have to be in no-intro and redump.
