### ISSUE TITLE
Vectrex Overlays 

### ISSUE THREAD

**Issue by clb1979** [libretro/ludo#368]
Hi !

Is it possible to have a preconfig overlay for each Vectrex game ?

**Comment by johnnyq** [comment]
@clb1979 Thanks for your feedback, basically @kivutar trys to keep the code as simple and as clean as possible and hasn't had a lot of time to work on the higher priority items so more than likely this will not be implemented anytime soon

**Comment by kivutar** [comment]
Sorry, no immediate plans to add this feature
