### ISSUE TITLE
LudOS Release

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#369]
Hi @kivutar I noticed Ludo 0.12.0 was release but LudOS wasn't updated. A few of us over here are really looking forward to the new dark mode and updated cores. Thank you again for this Fantastic project. This is the only All in One Emulation system I use. Just because its simply simple and looks very nice.

**Comment by Rstation4** [comment]
Im looking forward to more LudOS as well, especially since it can help introduce more people to retro game emulation. I installed it yesterday and Im seeing issues with it.

https://github.com/libretro/LudOS

**Comment by johnnyq** [comment]
Hi @Rstation4 I agree this is a very great project and is actively developed and will continue to be, @kivutar has been pretty busy and hasn't had much time to dedicate to the project recently. Development will happen again soon. Good things will come to the ones that wait hehe

**Comment by kivutar** [comment]
Here it is https://github.com/libretro/LudOS/releases/tag/v1.0-alpha33

Please tell me if it's working well :)

**Comment by johnnyq** [comment]
Just imaged it on my Pi3b+ So Far so good. No new bugs, ill keep testing to see if it fixed any old bugs and report back also I will try on my pi 4 after i play a few game here hehehe

**Comment by kivutar** [comment]
I found 2 issues:
- the rainbow screen is back during boot
- the performance of genesis plus gx is not 60fps anymore

**Comment by johnnyq** [comment]
@kivutar I noticed the rainbow and did notice genesis was a little slower as well. Most of the issues appear to be upstream. I cant wait for libreElec based on Debian 11. Im hoping that corrects a lot of things
