### ISSUE TITLE
Duped frame goes black after toggling fullscreen

### ISSUE THREAD

**Issue by hyarsan** [libretro/ludo#370]
Self-explanatory. A duped frame (passing NULL to video refresh callback) stops being rendered after toggling fullscreen.

**Comment by kivutar** [comment]
I think this is due to the GL context being reinitialized when we switch full screen.
Any idea how to avoid this?
What problems does it cause?

**Comment by kivutar** [comment]
I think we can live with this bug, it's only minor inconvenience.
