### ISSUE TITLE
Feature Request: Option to enable/disable overscan

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#371]
This would be a nice feature to add to the settings menu as my pi3b+ does not fill the entire screen of my monitor and has a black frame around the image. I am able to fix by modifying config.txt and uncommenting out disable_overscan=1. This is not a new issue just haven't reported it yet.

**Comment by kivutar** [comment]
It's weird, my config.txt already contains disable_overscan=1

**Comment by kivutar** [comment]
Fixed
