### ISSUE TITLE
New Xbox Wireless Controller (2020) doesn't work

### ISSUE THREAD

**Issue by ruffe972** [libretro/ludo#374]
I've tested only the Bluetooth connection method. Btw, this project is super cool.

**Comment by johnnyq** [comment]
Thanks for the suggestion, I'm sure it will get added. @kivutar has been nailing out the high priority items first.

**Comment by kivutar** [comment]
On what OS are you?

**Comment by ruffe972** [comment]
Sorry, forgot to mention the OS: it's Windows 10.

**Comment by popcar2** [comment]
Bump. There was a fork that fixed this but it never got approved, would be nice if someone can get it done because I would love to play wireless.

**Comment by Company-Captain** [comment]
Bump
  😳
👉👈

**Comment by kivutar** [comment]
Where is that fork?
The policy about joypads is that I can only support the ones I own. How can I check if I broke a joypad support in an update if I don't own it?
I do have a ton of pads at home, but not yet this one.

**Comment by Company-Captain** [comment]
Works now.

**Comment by kivutar** [comment]
Cool!

**Comment by ruffe972** [comment]
@kivutar, hello! Just downloaded Ludo on macOS, connected my Xbox Wireless Controller (2020) via Blutooth and it did not work.
