### ISSUE TITLE
Configurable font size

### ISSUE THREAD

**Issue by arthurlutz** [libretro/ludo#376]
Ludo looks awesome ! Congrats!

It would be nice if the font size were configurable (or are they already?). 

Thanks.

**Comment by johnnyq** [comment]
Hi @arthurlutz I agree with you I absolutely love the interface! The font sizes are not configurable. Ludo is about keeping the configuration and interface as minimal as possible and providing excellent defaults while putting the focus on your games. However Retroarch is much more configurable, but really the decision is up to @kivutar as he is the lead developer for Ludo.

**Comment by kivutar** [comment]
Hello @arthurlutz 

Thanks for the suggestion :)

but as @johnnyq explained the design goal is to not make Ludo that configurable.
