### ISSUE TITLE
This would be optimal for a GPi or Odroid Go

### ISSUE THREAD

**Issue by mtoensing** [libretro/ludo#379]
But sadly it does not run that well even on a Raspberry Pi 4. The GPi uses a Raspberry Pi Zero. But ludo looks so slick and nice...

**Comment by kivutar** [comment]
You can build LudOS for RPi1 and RPi0 quite easily I think

**Comment by mtoensing** [comment]
I tested Ludo on a PI4 and it was very, very slow

**Comment by kivutar** [comment]
I have a Pi3 at home and performance is full speed for everything.

Did you test this on a 4K display or with a bad power adapter?

**Comment by mtoensing** [comment]
The interface was fast but the emulation was slow.

**Comment by kivutar** [comment]
OK, which games on which emulator?

I have an Odroid Go Super now, I might add support for this in LudOS, Lakka already supports it.

**Comment by kivutar** [comment]
It is doable but requires too much work.

**Comment by mtoensing** [comment]
=(:::: this would have been a perfect fit for the popular retro handhelds.
