### ISSUE TITLE
0.12.1/2 macOS requirements changed?

### ISSUE THREAD

**Issue by aptonline** [libretro/ludo#381]
I've just looked to update my install of Ludo from 0.12.0 to 0.12.2 and I see that this no longer supports macOS 10.4.6 (Mojave) and requires 10.5.7 (Catalina) as a minimum.  As I run Ludo on a machine where I can continue to run 32 bit games (not supported in Catalina) this is disappointing.  Is there a technical reason to drop support for Mojave?

Thanks

**Comment by kivutar** [comment]
I wasn't aware that we dropped Mojave support at all.

The only thing that changed is that we switched the continuous delivery from travis to github, that might build the OSX version on a more recent OS which drops support for previous versions.

**Comment by aptonline** [comment]
Thanks for your reply. Is it possible this can be looked into? It’s a shame Mojave support was removed and I’m sure I’m not the only user who is still running it for the reasons stated. Thanks.

**Comment by kivutar** [comment]
Can you try to build ludo from source? It's quite easy on OSX

**Comment by aptonline** [comment]
I'll give it a try.  Is there no settings within continuous delivery where you can specify the output target for macOS?

**Comment by aptonline** [comment]
building works well thanks, how would I go about packaging this in an app bundle, I'm not familiar with Go.

**Comment by aptonline** [comment]
Trying the following which does build but not run:

```
mkdir -p Ludo.app/Contents/MacOS
go build -o Ludo.app/Contents/MacOS/ludo
```

**Comment by kivutar** [comment]
to package an app bundle, you can

```
OS=OSX ARCH=x86_64 VERSION=custom make dmg
```
