### ISSUE TITLE
Raspberry Pi 4 w/ Raspian currently lacks Full KMS support

### ISSUE THREAD

**Issue by maxengel** [libretro/ludo#383]
Currently, Raspian on the RPi4 is on kernel 5.4.79-v7l+, and does not have Full KMS support. `raspi-config` only lets you choose:
```
G1 Legacy
G2 GL (Fake KMS)
```

Running `rpi-update` bumps the kernel to 5.10.y, which then allows you to manually designate the Full KMS driver by modifying `/boot/config.txt` and changing `dtoverlay=vc4-fkms-v3d` to `dtoverlay=vc4-kms-v3d` and then rebooting.

I'm happy to contribute this to the documentation.

**Comment by kivutar** [comment]
OK, thanks for this report, it can be useful to other Raspbian users.

I think this problem will resolve by itself when they push a new default version of Raspbian.

**Comment by johnnyq** [comment]
I agree it will weed itself out
