### ISSUE TITLE
Raspian doesn't include Go by default and their package is outdated, so Ludo can't be built

### ISSUE THREAD

**Issue by maxengel** [libretro/ludo#384]
Raspian doesn't come with Go pre-installed. Additionally, the package available in the repo is outdated.

With the repo-provided package of golang, building Ludo will hang on `note: module requires Go 1.13`

In order to get Ludo to build you need to download the latest version directly from [here](https://golang.org/dl/). After downloading the correct build, you can run:
`sudo tar -C /usr/local -xzf go*.tar.gz`
`rm go*.tar.gz`
`export PATH=$PATH:/usr/local/go/bin`

and then the build process should work fine.

**Comment by kivutar** [comment]
Yes it's because raspbian is based on debian, which has a release cycle that lets you have software from 2 years ago.
There isn't much thing we can do about this. We provide releases for the RPi already :)
