### ISSUE TITLE
Prioritize gamepad as Joypad #0

### ISSUE THREAD

**Issue by maxengel** [libretro/ludo#385]
When a keyboard and controller are plugged-in, the controller should default to being Joypad #0. Otherwise, it becomes a game of plugging in accessories in the correct order so that the controller is mapped to Joypad #0 and then the keyboard is mapped after that.

**Comment by kivutar** [comment]
Well, it's been the case for me on all the laptop I tried, the joypad was always bind to port #0.
Where did you experience this bug?

**Comment by maxengel** [comment]
Apologies for not specifying. This is occurring on a Raspberry Pi 4 where I have a keyboard connected via USB in addition to a USB gamepad.

**Comment by kivutar** [comment]
Even on a RPi, with a keyboard, I get the first joypad assigned to the first player

**Comment by maxengel** [comment]
Ah, I think I found the issue. I am using an RF wireless keyboard with a dongle, and that is getting recognized as a joystick instead of as a keyboard, so it is mapped to Joystick 0 while my Xbox 360 controller is being mapped to Joystick 1.

Perhaps Ludo could prioritize joysticks with a valid config over ones without? this would solve the problem for me.

**Comment by kivutar** [comment]
Sorry, too hard to code this.. it would close the door to a lot of pads that would work out of the box without configuration.

**Comment by maxengel** [comment]
Got it, totally understand. Is there any way to contribute information about the wireless keyboard so it can be identified as one and not as a joystick?
