### ISSUE TITLE
After selecting a directory, exit the directory selection interface

### ISSUE THREAD

**Issue by maxengel** [libretro/ludo#389]
For example, if I go to: `Settings` > `Cores Directory` > and then navigate to a directory and choose `<Select this directory>` I then have to back out of the menu by tapping `Z`/`Back`. After making a selection, it would be nice if I returned to the settings list without having to navigate back up the directory tree.

**Comment by kivutar** [comment]
I agree that it would be nice.
Sadly, it makes the code too complex because of how I designed the explorer.
