### ISSUE TITLE
bios required list request

### ISSUE THREAD

**Issue by jjfmz42015** [libretro/ludo#394]
Specific builds should have a list of what bioses are required for that specific build.

would make things more user friendly/.

**Comment by Rstation4** [comment]
The 2 sources I use when it comes to Retroarch, Lakka and Ludo OS.
http://www.lakka.tv/doc/BIOSes/

and for a more detailed plethora of info check out the one by RetroArch Documents.
https://docs.libretro.com/library/bios/

Maybe there should be a link on the Ludo OS website to these 2 sources.

**Comment by kivutar** [comment]
It really depends on what emulators and roms you choose. BIOS are a complex topic.

For example pcsx_rearmed will refuse to boot some games if the bios required by mednafen is present.
Or duckstation will be ok to work with openbios, but then mednafen will refuse to boot...

The HLE bios of mgba will be fine, except for some games like Pokemon...

Etc...

And BIOS is a topic where making things user friendly without encouraging piracy is hard.
