### ISSUE TITLE
Request - Option to add controllers

### ISSUE THREAD

**Issue by Rstation4** [libretro/ludo#395]
Raspberry Pi 4 4gb
LudOS-RPi4.arm-1.0-alpha34

Right off the bat I could not use my Logitech F310 controller so I went ahead and searched for docs and files only to result in wasted time. There is no documentation either on how to configure or add controllers. Being able to add controllers on our own would be nice. Xbox 360 may have been the gold standard but it feels like that hardware is going to be obsolete, why not add more accessible and readily available controllers like the Logitech F310.

**Comment by Rstation4** [comment]
In my attempt to add a controller Im not sure where exactly how to do so.

I made a undev folder and tried placing a controller file in there.
![Ludo OS  dir](https://user-images.githubusercontent.com/73009731/111125475-8b4be800-8569-11eb-8a6f-061bf5bf96b0.png)

**Comment by kivutar** [comment]
Right now there is no way to add a controller, I will start thinking how to add this feature.
It's been requested many times.

**Comment by kivutar** [comment]
Closed in favor of https://github.com/libretro/ludo/issues/452
