### ISSUE TITLE
[Additional Documentation Request] for Ludo OS

### ISSUE THREAD

**Issue by Rstation4** [libretro/ludo#396]
For being a simplistic and beginner friendly emulator front end I cant really do much with it when it comes to the basic needs. Being able to add my own controller is just one of them. Examples

-how to add thumbnails
-removing playlist items (roms)
-parameters for roms being accepted to the playlist (some games didn't add to the list, bug perhaps)
-controller configuring (if its even a feature available)
-bios list for cores (at least mention to people they can use the documentation from Lakka and/or RA)

Someone who is completely new to emulation would be lost due to the lack of documentation and support there is for Ludo. Ive been able to get around a bit only due to my experience with Lakka Os.

**Comment by kivutar** [comment]
I started a documentation effort here: https://jean-andre-santoni.gitbook.io/ludo/

It's not yet covering all of your requests, but it partly addresses that.

**Comment by kivutar** [comment]
LudOS is now covered here https://jean-andre-santoni.gitbook.io/ludo/ludos/introduction
