### ISSUE TITLE
ROM scanner improvements

### ISSUE THREAD

**Issue by Rstation4** [libretro/ludo#397]
Raspberry Pi 4 B 4gb
LudOS-RPi4.arm-1.0-alpha34

I tested out the scanner by using a few roms for a few cores, some were zipped versions and some were not. Regular generic game roms were not being scanned correctly and added to the playlist. After trying it out on good straightforward roms, i tried it on unlicensed roms  and those failed to add as well. 

Would a manual scan like that of Lakka OS be hard to implement? I really liked how you can make your own playlist and cores to launch with it when it comes to roms that don't appear on the database. For example there are English Patched  PC-98 Touhou games that will not add when scanning.

Databases and scanning causes headaches when you have to take into consideration of Hacks, translated and patched roms. My experience with RPG Maker games is that I had change the label name as well when manually adding them otherwise all they would be in the list is a bunch of RPG_RT.ldb listings.

**Comment by kivutar** [comment]
I'm considering
- switching to a full manual scanning, only relying on dat for naming arcade games
- switching to xml dat from no-intro and fbneo instead of using the rdb format from RA

Maybe both. What do you think?

**Comment by kivutar** [comment]
The new scanner is based on XML dats. It covers more roms.
