### ISSUE TITLE
[Basic Features Request] Playlist edit, Manual Scan, logging

### ISSUE THREAD

**Issue by Rstation4** [libretro/ludo#398]
Raspberry Pi 4B 4gb
LudOS-RPi4.arm-1.0-alpha34

1. Being able to edit a playlist by removing entries or delete playlist entirely.
2. Manual Scanner - since some games are fan made, hacks or unlicensed the current scanner does not work on them. Even legit roms are having trouble being scanned and added to the list.
3. Logging - Mostly for troubleshooting

Update: I also tried Ludo on a Desktop PC on Linux Mint which needs some issues to be fixed as well.

**Comment by kivutar** [comment]
Closed in favor of:

 * Deleting playlists and entries has been implemented
 * Smart scanner: https://github.com/libretro/ludo/issues/453
 * Logging: https://github.com/libretro/LudOS/issues/23
