### ISSUE TITLE
How to use Ludo with EmulationStation

### ISSUE THREAD

**Issue by redromnon** [libretro/ludo#401]
Currently using Ludo v0.12.5 that I have downloaded from the releases for Linux. I am loving how lightweight and simple it is when compared to Retroarch. I am planning to integrate it with emulationstation.

Emulationstation has a `<command>` tag in the es_systems.cfg wherein we have to enter the emulator, its core and the ROM path (%ROM%) to launch the game.
Here, for Retroarch it's like - `<command> retroarch ~/cores/libretro-fceumm.so %ROM% </command> `

But since Ludo is an executable file, **what should I write for the command?**  `<command> ~/Ludo-Linux-x86_64-0.12.5/ludo ~/cores/libretro-fceumm.so %ROM%</command> ` is not working.
Please excuse me, I'm a newbie.

**Comment by kivutar** [comment]
Hi, you forgot to add the `-L` before the core path, in both retroarch and ludo commands

**Comment by redromnon** [comment]
Oh yes, I forgot to add the `-L`.  My bad.
But it still doesn't work - `<command> ~/Ludo-Linux-x86_64-0.12.5/ludo -L ~/cores/libretro-fceumm.so %ROM%</command>` 
Gives the **output** -
```
2021/04/06 07:23:35 Can't load game database: open ./database: no such file or directory
panic: open ./assets/font.ttf: no such file or directory

goroutine 1 [running, locked to thread]:
github.com/libretro/ludo/video.(*Video).Configure(0xc000236000, 0xc000236000)
	/home/runner/work/ludo/ludo/video/video.go:113 +0xc38
github.com/libretro/ludo/video.Init(...)
	/home/runner/work/ludo/ludo/video/video.go:61
main.main()
	/home/runner/work/ludo/ludo/main.go:100 +0x478
Terminated
```

**Comment by redromnon** [comment]
Instead this command is **working perfectly** and Ludo launches straight into the game - `cd  ~/Ludo-Linux-x86_64-0.12.5  &&  ./ludo  -L  ~/ludo/cores/fceumm_libretro.so  %ROM%`

Looks like I have to go to the directory and then execute the file with core and ROM. But what's the difference? Shouldn't the above command work too?

**Comment by kivutar** [comment]
The difference is that ludo is looking for an asset, the font, in a path relative to where you launch it.
You can workaround this by setting an absolute path for the asset directory in ludo settings file.

**Comment by redromnon** [comment]
Thanks! I'll try that. But I'll probably stick to above command.
So should I close the issue?
