### ISSUE TITLE
PSX games not loading from playlist in LudOS

### ISSUE THREAD

**Issue by maxengel** [libretro/ludo#404]
**Steps to Reproduce**
1. Flash LudOS v Alpha 37 to an SD card
2. Insert SD card into RPi 4, 8GB
3. After initial installation, load ROMs and Bioses to appropriate directories
4. Add games from directories to generate playlists for systems
5. Select Playstation and launch a game
6. Starting the game causes the system to hang

While loading doesn't work from the playlist, they do work if you load a core and select the game manually.

**Comment by kivutar** [comment]
Try to remove the bios? pcsx_rearmed can have problems running on the prefered bios of mednafen.

**Comment by maxengel** [comment]
@kivutar removing the PSX BIOS file did solve the problem. I'm using scph5500.bin but also have scph5501.bin and scph5502.bin as well if you'd like me to do any testing.
