### ISSUE TITLE
Failing to launch ludo on clockworkpi gameshell

### ISSUE THREAD

**Issue by arthurlutz** [libretro/ludo#405]
Using a debian bullseye image for the clockworkpi https://github.com/wolfallein/clockworkpi-debian/ I successfully compiled ludo but am failing to launch it.  Mention of KMS in the README got me thinking that maybe it could be launched without Xorg  (running retroarch without Xorg works, and also managed to launch EmulationStation that way). 

```
cpi@clockworkpi :~/ludo$ uname -a
Linux clockworkpi  5.7.0-clockworkpi-cpi3-g5c715d2cd-dirty #1 SMP Sun Jul 12 20:21:02 CEST 2020 armv7l GNU/Linux

cpi@clockworkpi :~/ludo$ go version
go version go1.15.9 linux/arm

cpi@clockworkpi :~/ludo$ ./ludo
2021/04/12 15:02:50 PlatformError: X11: The DISPLAY environment variable is missing
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0x838eec, 0x2, 0x2, 0x0, 0x0)
	/home/cpi/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20201108214237-06ea97f0c265/error.go:174 +0x1a4
github.com/go-gl/glfw/v3.3/glfw.CreateWindow(0x3c0, 0x21c, 0x41fb7d, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/cpi/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20201108214237-06ea97f0c265/window.go:350 +0x150
github.com/libretro/ludo/video.(*Video).Configure(0x8a00e0, 0x8a0000)
	/home/cpi/ludo/video/video.go:90 +0x50
github.com/libretro/ludo/video.Init(...)
	/home/cpi/ludo/video/video.go:61
main.main()
	/home/cpi/ludo/main.go:101 +0x3cc
```

Will probably try it out with Xorg, but I'm curious about this "Full KMS" mode referred in the README.

**Comment by arthurlutz** [comment]
Got it to work with Xorg :tada: . I'd love to have your feedback on the "Full KMS" feedback. 

![Peek 2021-04-12 19-09](https://user-images.githubusercontent.com/108437/114447071-4485f800-9bd2-11eb-85c5-d42cb5a14b59.gif)

More info on how I got it to run with Xorg over here : https://forum.clockworkpi.com/t/clockworkpi-debian-compiling-and-running-ludo-libretro-go-launcher/6487

(yes I know you've already said it is not designed for 320x240 resolution in #376 )

**Comment by kivutar** [comment]
Nice! Yeah Ludo still require X11.

I'm not sure how GLFW can run on DRM/KMS.

**Comment by arthurlutz** [comment]
@kivutar I was under the impression it might work without X11 by the "the experimental VC4 OpenGL support (Full KMS) " mention in the README, but I have no idea how it works or anything... I know some SDL2 apps work without X11...

**Comment by kivutar** [comment]
I don't know how SDL2 does things, but Ludo uses GLFW3. They have a lot of docs, I see mention of X11 and Wayland, but not so much of  DRM/KMS of GBM. Maybe through EGL it would be possible?
