### ISSUE TITLE
Request: LudOS for Anbernic RG351P and RG351V Handhelds

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#406]
These are best handhelds ever and it looks like lakka works on the Anbernic 351V and 351P so i'm wondering how much work it would be to port the Fantastic LudOS over to these fantastic handhelds. I could help with testing just let me know where to begin thank you for this wonderful emulation experience!!

**Comment by kivutar** [comment]
Hard because most of the arm boards are using DRM/KMS + GLES, while Ludo is X11 + OpenGL.

I have an Odroid Go Super at home, and I didn't port LudOS to it because of this, too much work.

Sorry but use Lakka instead.
