### ISSUE TITLE
(Ludo Desktop Linux) game added double playlist entries bug

### ISSUE THREAD

**Issue by ghost** [libretro/ludo#421]
Desktop PC
OS: Linux Mint 20.1
Ludo: Ludo-Linux-x86_64-0.14.0  (bug also in older version)

When adding a rom to the playlist for Final Burn Neo it added 2 entries, even the thumbnails had two entries for my one rom. For these CSV files can they be opened with other programs for ease of use?

FBNeo CSV file
[FBNeo - Arcade Games.csv](https://github.com/libretro/ludo/files/6504345/FBNeo.-.Arcade.Games.csv)

**Comment by kivutar** [comment]
Thanks, will look into it

**Comment by johnnyq** [comment]
I have the same issue as well on LUDOS for Raspberry pi 3b+

**Comment by kivutar** [comment]
I can reproduce

**Comment by igoracmelo** [comment]
@kivutar This happens because the function `FindByCRC` doesn't stop on first match.
I could make a PR to end the function on the first match, but I don't know if that is the desired behavior...

**Comment by tompruitt** [comment]
This should be fixed.
Do you want to check if its fixed, or can this be closed? @ghost

**Comment by igoracmelo** [comment]
Should be solved by #540
