### ISSUE TITLE
Failure to scan and add zip rom (Ludo Linux)

### ISSUE THREAD

**Issue by Rstation4** [libretro/ludo#422]
Desktop PC
OS: Linux Mint 20.1 Cinnamon
Ludo: Ludo-Linux-x86_64-0.14.0

Scanning a zipped snes rom that did not add itself to the playlist. It is a working rom that I can confirm that works when launching with Retroarch (1.9.1).

Requesting Manual Scan Feature

**Comment by kivutar** [comment]
Is it a No-Intro ROM?

**Comment by Rstation4** [comment]
It' "Super Adventure Island" but Im unsure about it being a No-intro. As for the English fan translation of Touhou games (1,2,3,4,5) for PC-98 how would I be able to add those to the PC-98 playlist?

**Comment by kivutar** [comment]
For now you have to create playlist manually for any rom that is:
- not no-intro
- patched

Playlists are in ~/.ludo/playlists and can be edited with a simple text editor
