### ISSUE TITLE
Ludo emulator lag (Ludo-Linux-x86_64-0.14.0)

### ISSUE THREAD

**Issue by Rstation4** [libretro/ludo#423]
Dekstop PC running Linux Mint 20.1 Cinnamon Edition
Cinnamon Version: 4.8.6
Linux Kernel: 5.4.0-70-lowlatency

Ludo: Ludo-Linux-x86_64-0.14.0

So far I've tried Snes and a FBNeo rom and they both have noise and gameplay lag.

**Comment by kivutar** [comment]
Is your screen more than 60Hz?

**Comment by Rstation4** [comment]
Do you mean the monitor I use? I posted a image on the display settings of it. Is there a way to generate logs with Ludo?
![Monitor  D settings](https://user-images.githubusercontent.com/73009731/119093482-9d606180-b9c4-11eb-9224-67aba22d92c2.png)

**Comment by kivutar** [comment]
Your screen is 30Hz, Ludo requires 60Hz to pace emulators properly

**Comment by Rstation4** [comment]
I saw that my HDMI cable is the culprit that did not allow me to get the full 60.00 Hz, While I did not retest with Ludo, I retested using RetroArch and the choppyness that was occurring there stopped as well.

**Comment by kivutar** [comment]
We can because supporting 30Hz would make the code of ludo too complex
