### ISSUE TITLE
Misspelling in the FAQ on the website.

### ISSUE THREAD

**Issue by KarmicBacklash** [libretro/ludo#425]
This is a simple one, on the website for Ludo there is a small type. It says "Some design choices are different. For examplem we support less cores, and choose cores for the user. The cores are packaged in the frontend so no additional step is required to launch a game."

The type being the extra m at the end of example. I'd submit a fix myself but I can't find the offending code in the repo.

**Comment by kivutar** [comment]
Thanks, fixed here https://github.com/libretro/ludo.libretro.com/commit/a95d5228e74dc553ec1a47a240bd8a03f5d4920b
