### ISSUE TITLE
mednafen pce core accurate

### ISSUE THREAD

**Issue by Eggo-dotcom** [libretro/ludo#428]
mednafen pce core accurate exists now. 

possible to switch to this rather than fast version?

its not that heavy and is better

**Comment by kivutar** [comment]
Does it run full speed on a RPi2? Because this is the weakest device Ludo tries to support.

What games are fixed by the accurate version?

Is it the core named mednafen_pce_libretro on the buildbot?

**Comment by Eggo-dotcom** [comment]
Yes thats the core. 

The accurate core is 100% accurate proper timings perfect experience. Fast was developed for low power cpus. Uses speed hacks and compromises. It still runs 99% of games just timings etc can be off. Handy if you have a low low power chip but any cpu on a pc from the last decade can run the accurate core. The accurate core take slightly less cpu time than sgx core you use.

**Comment by kivutar** [comment]
OK, testing this now, thanks for the advice.

**Comment by Eggo-dotcom** [comment]
I dont own a Pi to test it on wish I knew, however if other core you use do I think it does.

If the SGX core runs fine on Pi it will as well as its less cpu intense than SGX core.

**Comment by Eggo-dotcom** [comment]
interesting, i just replaced your supplied mednafen_pce_fast_libretro.dll with mednafen_pce_libretro.dll renamed to mednafen_pce_fast_libretro.dll and it all works fine. Didnt think it would be that simple so really I guess if a user wants the different core they can do this.

**Comment by kivutar** [comment]
There is a cleaner way than this, you can just put the core in the core folder without renaming it, and edit ~/.ludo/settings.toml to use it as default core for the 3 PCE playlists.

Anyway, I have a PR to switch to the accurate core. We'll know soon if it's fast enough as I have a Pi at home.

**Comment by Eggo-dotcom** [comment]
Thanks for the new core!
