### ISSUE TITLE
GLFW 3.3 Beta

### ISSUE THREAD

**Issue by RobLoach** [libretro/ludo#44]
Discussion about GLFW 3.3 Beta:
https://bit.ly/2nTqRQJ

It's not quite out yet.

**Comment by RobLoach** [comment]
Oh, we're using 3.2... I believe I'm thinking of 3.3 betas, with the gamepad re-work.

**Comment by RobLoach** [comment]
https://bit.ly/2nTqRQJ

**Comment by kivutar** [comment]
I've tried it, there are issues during linking for now.

**Comment by kivutar** [comment]
GLFW 3.3 has been released. I hope the go binding will be fixed on OSX soon.
