### ISSUE TITLE
Feature Request - Menu sound

### ISSUE THREAD

**Issue by deivkiau** [libretro/ludo#440]
## Description
Add option to turn ON navigation sounds.

## Example
1. Ludo

https://user-images.githubusercontent.com/42415009/121481882-3e937400-c9d5-11eb-9a11-d175df6fca58.mp4

2. PS3 (can't reproduce, but similar to Ludo)

**Comment by johnnyq** [comment]
You can Turn Menu Sound off and on by selecting settings > Menu Audio Volume then press left to turn the volume all the way down.

**Comment by kivutar** [comment]
If he requests this feature in RetroArch, this should be in the RetroArch tracker no?
