### ISSUE TITLE
Video filters: no visible difference betweeen 'raw' and 'pixel perfect'

### ISSUE THREAD

**Issue by bycrean** [libretro/ludo#442]
I tested both video filters and could see no difference for TurboGrafx-16 and Super Nintendo games. Is there a difference? If yes, what is it? If not, why are there two different names for the same video filter?

**Comment by kivutar** [comment]
Raw is nearest neighbor interpolation.
Pixel perfect is sharp bilinear filtering.

You will only be able to notice a difference on very low resolution screens, where sharp bilinear helps mitigating the lack of alignment between the game pixel grid and your screen grid.

This article explains it in details https://filthypants.blogspot.com/2017/01/shaders-for-sharpest-pixels.html

**Comment by bycrean** [comment]
@kivutar Thanks for the clarification. Maybe it would be helpful to extend the name of the filter: 'pixel perfect (good for low-res screens)'.

**Comment by kivutar** [comment]
I think we'll need to find self explanatory names.
When we need to explain what settings are, it's usually a bad sign...
