### ISSUE TITLE
Make entries in 'Load Core' list more readable

### ISSUE THREAD

**Issue by bycrean** [libretro/ludo#447]
In the 'Load Core' menu it would be helpful (especially for non-experts) to have the cores listed in a more readable form that also states which console it emulates - for example 'fceumm (Nintendo Entertainment System)' instead of 'fceumm_libreto.dll'. This way, users like me wouldn't have to look up online which core they must load.

**Comment by johnnyq** [comment]
Very Good idea!

**Comment by kivutar** [comment]
I totally agree.

**Comment by bycrean** [comment]
I'm glad both of you like the suggestion.

**Comment by johnnyq** [comment]
Wow! That looks so much better good catch @bycrean and excellent implementation @kivutar
