### ISSUE TITLE
BUG: Crash Occurs when you run GBA then choose Sega MegaDrive or SNES

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#456]
Loading a GBA Game on initial boot then loading a SNES or Sega Megadrive game causes a crash in all instances everytime. Now if you load snes game first then a GBA game the crash doesnt happen. This has to be performed on initial boot.

**Comment by johnnyq** [comment]
Possibly be related to #184 
Issue #184 also need reopened as this is continuing to happen.
Let me know if I can test anything or be of any more help

**Comment by kivutar** [comment]
Mmmmh not for me. It must be related to some memory stuff.

**Comment by johnnyq** [comment]
It may possibly be. I should have specified, it looks like it affects Raspberry Pi 3B+ I haven't tested with pi 4 or pc yet I will test and report back

**Comment by kivutar** [comment]
Cool
