### ISSUE TITLE
adding Fast Forward function into PS4 Controller?

### ISSUE THREAD

**Issue by hentaiikidd** [libretro/ludo#464]
Hi guys,

I'm using DualShock 4 Controller to play game on **ludo** on MacOS Big Sur, 11.5.2. The version of **ludo** I'm using is the one I download from your website https://ludo.libretro.com/.
I like it a lot. Play with wireless controller make it feel a lot better than using a keyboard. But whenever I want to switch fast forward on/off, I have to come to my computer and hit the space. 

Is there a way to add the big rectangle button between SHARE and OPTION buttons on DualShock 4 Controller, so I can easily Fast Forward it on my controller? Because I think the Fast Forward function is the only one that not on the controller right now, even the PS1 games do not use that rectangle button.

If I have to manually configure it, could you please guide me, I'm new to this coding stuff?

Thank you a lot!

**Comment by kivutar** [comment]
I solve this as we found a solution that works for you, and there is no easy way to do it in ludo.
