### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Mejans** [libretro/ludo#476]
Hello,

I wanted to contribute by sending a translation but I couln't find them =/
Ludo is not multilingual ?

Best regards

**Comment by kivutar** [comment]
Hi, no it's not multilingual
The goal is to keep the code small
But thank you for your interest in helping

**Comment by donmor** [comment]
Actually, having Unicode and basic i18n implementation is just great enough. Let them create their own translations inside assets.

**Comment by Mejans** [comment]
Could this be reconsidered? Internationalisation helps accessibility a lot.

**Comment by donmor** [comment]
Well they should work on unicode first... They hardcoded ch(32) to ch(256) to be rendered.

**Comment by Mejans** [comment]
So an English word like Façade, coming from French and from Occitan, cannot be rendered?
