### ISSUE TITLE
Sort cores by system name first

### ISSUE THREAD

**Issue by petete1** [libretro/ludo#490]
Rigth now Ludo sorts cores by the name of the emulator it uses. Instead I propose that it should be sorted by the name of the system first followed by the name of the emulator. This way it would be easier to find the cores you want and see if there's more than one core for the system.

Now:
Beetle PlayStation
...
PCSX Rearmed (PlayStation)

Should be:
PlayStation (Beetle PlayStation)
PlayStation (PCSX Rearmed)

**Comment by kivutar** [comment]
I merged the PR that fixes this, thanks
