### ISSUE TITLE
Ludo Doesn't Detect .a26 Files While Scanning

### ISSUE THREAD

**Issue by Legomountain14** [libretro/ludo#519]
Platform: macOS 14.2.1 & macOS 12.7.1

When I use "Scan This Directory" or directly select a file, it does not detect any Atari 2600 games. I checked the sums and file names against the "Atari - 2600.dat" file, and they all match. Very strange.

I am going to look through the "scanner.go" file for debugging.

**Comment by bagelbyheart** [comment]
This can probably be closed once the pull request is approved. It's a very simple update.
