### ISSUE TITLE
mupen64_plus core Invalid ELF header

### ISSUE THREAD

**Issue by ghost** [libretro/ludo#532]
![Snapshot_2024-03-03_20-04-38](https://github.com/libretro/ludo/assets/160610515/ba74a179-8c4e-4810-8da9-cf855e29400d)

**Comment by rusberiaosa** [comment]
x86_64 architecture

**Comment by kivutar** [comment]
I can't reproduce :/
![image](https://github.com/libretro/ludo/assets/442722/1059fbdb-2643-47b5-b53f-59ed8964dd84)

**Comment by kivutar** [comment]
User don't exist anymore.
