### ISSUE TITLE
Controller Database

### ISSUE THREAD

**Issue by RobLoach** [libretro/ludo#87]
I see a whole bunch of controller mappings defined in /input....

Could this be a place to use [GLFW Controller Database](https://github.com/sriharshachilakapati/GLFW-Controller-Database)? Unsure what it would really accomplish that the definitions do right now, however.

Found [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) too, which has similar goals.

**Comment by kivutar** [comment]
I will definitely give it a try when GLFW 3.3 is released.

I have a few doubts about how they handle the tricky controllers, like the DS4 mess on the different versions of the linux kernel. And also controllers that have the same name.

I don't see them supporting vid and pid (we don't support it either). So we'd rather use retroarch-joypad-config which is just better conceptually. The issue with retroarch-joypad-config is that we're merging PRs without checking anything.

My idea for Ludo is to support only 5 to 10 controllers, but support them fully (With button icons) and on the long run without regression.

**Comment by kivutar** [comment]
I close this in favor of the GLFW 3.3 issue
