### ISSUE TITLE
open32AL.dll missing when launching on Win7

### ISSUE THREAD

**Issue by kivutar** [libretro/ludo#89]

**Comment by RobLoach** [comment]
Confirmed.
```
---------------------------
ludo.exe - System Error
---------------------------
The code execution cannot proceed because OpenAL32.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
```

**Comment by kivutar** [comment]
The openal binding in go only links it dynamically because of the license.
We may fork their repo to change this.
Or we copy the dll next to the executable.

**Comment by kivutar** [comment]
@RobLoach @Arnochocobo can you try the latest release? It has the OpenAL32.dll included. I'd like to know if it fixes the bug.

**Comment by mudlord** [comment]
How does Go handle linking with C code, or can it just not do that?

**Comment by RobLoach** [comment]
With [cgo](https://golang.org/cmd/cgo/)....
https://github.com/libretro/ludo/blob/master/libretro/libretro.go

I can test the Windows release again. Will re-install my Windows partition tonight.

**Comment by kivutar** [comment]
It is done with magic comments, you can pass linker options like `-L`. See https://stackoverflow.com/questions/16747021/how-do-you-statically-link-a-c-library-in-go-using-cgo

The OpenAL binding that I'm using was initially made for Android, and for proprietary apps. OpenAL being LGPL, it forces you to use dynamic linking in proprietary apps.
I don't think this restriction applies to open source software like Ludo, where users can rebuild the whole thing and link their own OpenAL implementation.

See https://github.com/golang/mobile/blob/master/exp/audio/al/al_notandroid.go#L10-L15

So this binding is using dynamic linking. We may have to modify it to use static linking instead.

Or, distributing the DLL alongside the exe.

On OSX, we can assume that OpenAL is present in the system. On Linux and windows, not.

**Comment by RobLoach** [comment]
Now able to launch Ludo, but unable to load a core....

```
ludo -L "C:\Users\rob_l\Desktop\Ludo\cores\nestopia_libretro.dll" "10-Yard Fight (Japan).zip"                             panic: Failed to load C:\Users\rob_l\Desktop\Ludo\cores\nestopia_libretro.dll: The specified module could not be found.                                                                                                                                                                                                    goroutine 1 [running, locked to thread]:                                                                                main.main()                                                                                                                     C:/Users/travis/gopath/src/github.com/libretro/ludo/main.go:101 +0x604                                                                                                                                                                  
```

The nestopia_libretro.dll file is there. This happens in both the command line, and the UI. Every time I load up this operating system, I get frustrated. Going to give up on Windows. Good bye partition... GG

Launching Ludo on Windows works great with the OpenAL32 binary there, so I'd consider this issue resolved.

**Comment by Zewwy** [comment]
I decided to quickly test Ludo on Windows 7 x64 VM I have.

First boot failed with vcruntime140.dll missing, so would be nice to state dependencies in this case: Microsoft Visual C++ 2015 Redistributable Update 3 RC

Then after that all I get is:

panic: APIUnavailable: WGL: The Driver does not appear to support OpenGL, so this is more than likely due to with VMware video drivers:  VMware SVGA 3D...

but then... "The VMware SVGA 3D graphics driver provides support for DirectX 9.0c and OpenGL 2.1. This driver is supported on Windows 7 for 2D and 3D." [Source](https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/whitepaper/vmware-horizon-view-graphics-acceleration-deployment-white-paper.pdf)

So not sure why that failed... I can try the x86 version on my netbook....

**Comment by kivutar** [comment]
@Zewwy x86_64 means 64bit only, this version won't run on 32bit.

@RobLoach I will test this today.

However, this thread is not about Windows issues in general, it's about the OpenAL issue on Windows. So let's not discuss unrelated issues there.

**Comment by kivutar** [comment]
Closed because @RobLoach tested it and it works
